msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2016-04-19 06:56+0000\n"
"PO-Revision-Date: 2024-07-02 13:23\n"
"Last-Translator: Ubuntu Belarusian Translators Team <Unknown>\n"
"Language-Team: Ukrainian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-05-24 06:30+0000\n"
"X-Generator: Launchpad (build 0e1f616671af724398db43b36ddfb3ed1f2682ec)\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: uk\n"
"X-Crowdin-File: /main/noble/en_GB/po-glance_glance-be.po\n"
"X-Crowdin-File-ID: 341\n"
"Language: uk_UA\n"

#: glance/location.py:101
msgid "Invalid location"
msgstr ""

#: glance/location.py:333
msgid "Invalid locations"
msgstr ""

#: glance/store/__init__.py:667
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/location.py:440
msgid "Signature verification failed"
msgstr ""

#: glance/store/__init__.py:739
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr ""

#: glance/notifier.py:239 glance/api/v1/upload_utils.py:184
#: glance/api/v2/image_data.py:107
#, python-format
msgid "Image storage media is full: %s"
msgstr ""

#: glance/notifier.py:243 glance/api/v1/upload_utils.py:193
#: glance/api/v2/image_data.py:128
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr ""

#: glance/notifier.py:248
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:254
#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:261
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:267
#, python-format
msgid "Image %(image_id)s could not be found after upload. The image may have been deleted during the upload: %(error)s"
msgstr ""

#: glance/notifier.py:274
#, python-format
msgid "Failed to upload image data for image %(image_id)s due to HTTP error: %(error)s"
msgstr ""

#: glance/notifier.py:281
#, python-format
msgid "Failed to upload image data for image %(image_id)s due to internal error: %(error)s"
msgstr ""

#: glance/schema.py:58
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr ""

#: glance/scrubber.py:42 glance/store/__init__.py:58
msgid "The amount of time in seconds to delay before performing a delete."
msgstr ""

#: glance/scrubber.py:40
msgid "The size of thread pool to be used for scrubbing images. The default is one, which signifies serial scrubbing. Any value above one indicates the max number of images that may be scrubbed in parallel."
msgstr ""

#: glance/store/__init__.py:53
msgid "Turn on/off delayed delete."
msgstr ""

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: glance/scrubber.py:51 glance/registry/client/v1/api.py:34
msgid "Whether to pass through headers containing user and tenant information when making requests to the registry. This allows the registry to use the context middleware without keystonemiddleware's auth_token middleware, removing calls to the keystone auth service. It is recommended that when using this option, secure communication between glance api and glance registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/scrubber.py:64
msgid "Loop time between checking for new items to schedule for delete."
msgstr ""

#: glance/scrubber.py:72
msgid "Run as a long-running process. When not specified (the default) run the scrub operation once and then exits. When specified do not exit and run scrub on wakeup_time interval as specified in the config."
msgstr ""

#: glance/api/authorization.py:197 glance/api/authorization.py:380
msgid "Public images do not have members."
msgstr ""

#: glance/api/authorization.py:118 glance/api/authorization.py:129
#, python-format
msgid "You cannot get image member for %s"
msgstr ""

#: glance/api/authorization.py:137
#, python-format
msgid "You cannot delete image member for %s"
msgstr ""

#: glance/api/authorization.py:146
#, python-format
msgid "You cannot add image member for %s"
msgstr ""

#: glance/api/authorization.py:155
#, python-format
msgid "You cannot update image member %s"
msgstr ""

#: glance/api/authorization.py:174
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr ""

#: glance/api/authorization.py:192
msgid "You are not permitted to create image members for the image."
msgstr ""

#: glance/api/authorization.py:213
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr ""

#: glance/api/authorization.py:223
msgid "You are not permitted to modify locations for this image."
msgstr ""

#: glance/api/authorization.py:247
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr ""

#: glance/api/authorization.py:251
msgid "You are not permitted to modify this image."
msgstr ""

#: glance/api/authorization.py:264
msgid "You are not permitted to modify tags on this image."
msgstr ""

#: glance/api/authorization.py:305
msgid "You are not permitted to delete this image."
msgstr ""

#: glance/api/authorization.py:316
msgid "You are not permitted to upload data for this image."
msgstr ""

#: glance/api/authorization.py:342
msgid "You are not permitted to deactivate this image."
msgstr ""

#: glance/api/authorization.py:346
msgid "You are not permitted to reactivate this image."
msgstr ""

#: glance/api/authorization.py:350 glance/api/authorization.py:354
#: glance/api/authorization.py:358
msgid "You are not permitted to set status on this task."
msgstr ""

#: glance/api/authorization.py:420
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""

#: glance/api/authorization.py:515
msgid "You are not permitted to delete this namespace."
msgstr ""

#: glance/api/authorization.py:519
msgid "You are not permitted to update this namespace."
msgstr ""

#: glance/api/authorization.py:545
#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr ""

#: glance/api/authorization.py:604
msgid "You are not permitted to delete this object."
msgstr ""

#: glance/api/authorization.py:608
msgid "You are not permitted to update this object."
msgstr ""

#: glance/api/authorization.py:633
#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr ""

#: glance/api/authorization.py:696
msgid "You are not permitted to delete this meta_resource_type."
msgstr ""

#: glance/api/authorization.py:722
#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr ""

#: glance/api/authorization.py:780
msgid "You are not permitted to delete this property."
msgstr ""

#: glance/api/authorization.py:784
msgid "You are not permitted to update this property."
msgstr ""

#: glance/api/authorization.py:809
#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr ""

#: glance/api/authorization.py:867
msgid "You are not permitted to delete this tag."
msgstr ""

#: glance/api/authorization.py:871
msgid "You are not permitted to update this tag."
msgstr ""

#: glance/api/authorization.py:892
msgid "Owner must be specified to create a tag."
msgstr ""

#: glance/api/authorization.py:895
#, python-format
msgid "You are not permitted to create a tag in the namespace owned by '%s'"
msgstr ""

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr ""

#: glance/api/policy.py:220 glance/quota/__init__.py:343
#: glance/store/__init__.py:662
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/versions.py:27 glance/api/glare/versions.py:28
msgid "Public url to use for versions endpoint. The default is None, which will use the request's host_url attribute to populate the URL base. If Glance is operating behind a proxy, you will want to change this to represent the proxy's URL."
msgstr ""

#: glance/api/glare/v0_1/glare.py:121
#, python-format
msgid "The format of the version %s is not valid. Use semver notation"
msgstr ""

#: glance/api/glare/v0_1/glare.py:188
#, python-format
msgid "Invalid Content-Type for work with %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:225
msgid "Invalid request PATCH for work with blob"
msgstr ""

#: glance/api/glare/v0_1/glare.py:239
#, python-format
msgid "Denying attempt to upload artifact because it exceeds the quota: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:263
#, python-format
msgid "Failed to find artifact %(artifact_id)s to delete"
msgstr ""

#: glance/api/glare/v0_1/glare.py:267
#, python-format
msgid "Artifact %s could not be deleted because it is in use: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:296
msgid "Unable to PUT to non-empty collection"
msgstr ""

#: glance/api/glare/v0_1/glare.py:299
msgid "Index is out of range"
msgstr ""

#: glance/api/glare/v0_1/glare.py:322
#, python-format
msgid "Not a blob property '%s'"
msgstr ""

#: glance/api/glare/v0_1/glare.py:330
#, python-format
msgid "Not a list property '%s'"
msgstr ""

#: glance/api/glare/v0_1/glare.py:344
msgid "Error in store configuration. Adding artifacts to store is disabled."
msgstr ""

#: glance/api/glare/v0_1/glare.py:366
#, python-format
msgid "Artifact storage media is full: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:374
#, python-format
msgid "Artifact exceeds the storage quota: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:382
#, python-format
msgid "The incoming artifact blob is too large: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:390
#, python-format
msgid "Insufficient permissions on artifact storage media: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:423
msgid "Index is required"
msgstr ""

#: glance/api/glare/v0_1/glare.py:431
msgid "Not a list property"
msgstr ""

#: glance/api/glare/v0_1/glare.py:435
msgid "Not a downloadable entity"
msgstr ""

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:287
msgid "Body expected in request."
msgstr ""

#: glance/api/glare/v0_1/glare.py:577
#, python-format
msgid "Invalid headers \"Content-Type\": %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:615
#, python-format
msgid "Invalid json body: %s"
msgstr ""

#: glance/api/glare/v0_1/glare.py:628
msgid "Only list indexes are allowed for blob lists"
msgstr ""

#: glance/api/glare/v0_1/glare.py:649
msgid "Limit param must be an integer"
msgstr ""

#: glance/api/glare/v0_1/glare.py:653
msgid "Limit param must be positive"
msgstr ""

#: glance/api/glare/v0_1/glare.py:657
#, python-format
msgid "Limit param must not be higher than %d"
msgstr ""

#: glance/api/glare/v0_1/glare.py:667
#, python-format
msgid "Invalid sort key: %(sort_key)s. If type version is not set it must be one of the following: %(available)s."
msgstr ""

#: glance/api/glare/v0_1/glare.py:678
#, python-format
msgid "Invalid sort key: %(sort_key)s. You cannot sort by this property"
msgstr ""

#: glance/api/v2/images.py:498 glance/api/v2/tasks.py:134
#, python-format
msgid "Invalid sort direction: %s"
msgstr ""

#: glance/api/middleware/context.py:28
msgid "When true, this option sets the owner of an image to be the tenant. Otherwise, the owner of the  image will be the authenticated user issuing the request."
msgstr ""

#: glance/api/middleware/context.py:36
msgid "Allow unauthenticated users to access the API with read-only privileges. This only applies when using ContextMiddleware."
msgstr ""

#: glance/api/middleware/context.py:41
msgid "Limits request ID length."
msgstr ""

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr ""

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr ""

#: glance/api/middleware/context.py:125
#, python-format
msgid "x-openstack-request-id is too long, max size %s"
msgstr ""

#: glance/api/v1/controller.py:41 glance/api/v1/members.py:76
#, python-format
msgid "Image with identifier %s not found"
msgstr ""

#: glance/api/v1/controller.py:46
msgid "Forbidden image access"
msgstr ""

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is deactivated"
msgstr ""

#: glance/api/v1/controller.py:59
#, python-format
msgid "Image %s is not active"
msgstr ""

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr ""

#: glance/api/v1/controller.py:93
#, python-format
msgid "Data for image_id not found: %s"
msgstr ""

#: glance/api/v1/images.py:87
#, python-format
msgid "Invalid time format for %s."
msgstr ""

#: glance/api/v1/images.py:73
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:78
#, python-format
msgid "Invalid container format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:94
msgid "Invalid mix of disk and container formats. When setting a disk or container format to one of 'aki', 'ari', or 'ami', the container and disk formats must match."
msgstr ""

#: glance/api/v1/images.py:83
#, python-format
msgid "Image name too long: %d"
msgstr ""

#: glance/api/v1/images.py:139
#, python-format
msgid "Invalid checksum '%s': can't exceed 32 characters"
msgstr ""

#: glance/api/v1/images.py:172
#, python-format
msgid "The limit has been exceeded on the number of allowed image properties. Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""

#: glance/api/v1/images.py:194 glance/api/v1/images.py:238
#: glance/api/v1/images.py:272
#, python-format
msgid "Property '%s' is protected"
msgstr ""

#: glance/api/v1/images.py:388
msgid "This operation is currently not permitted on Glance images details."
msgstr ""

#: glance/api/v1/images.py:380
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr ""

#: glance/api/v1/images.py:477
#, python-format
msgid "External sources are not supported: '%s'"
msgstr ""

#: glance/api/v1/images.py:479
msgid "External source should not be empty"
msgstr ""

#: glance/api/v1/images.py:493
#, python-format
msgid "Required store %s is invalid"
msgstr ""

#: glance/api/v1/images.py:505 glance/api/v1/images.py:877
#, python-format
msgid "Invalid location %s"
msgstr ""

#: glance/api/v1/images.py:528
#, python-format
msgid "An image with identifier %s already exists"
msgstr ""

#: glance/api/v1/images.py:621
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr ""

#: glance/api/v1/images.py:542
msgid "Forbidden to reserve image."
msgstr ""

#: glance/api/v1/images.py:578
msgid "Content-Type must be application/octet-stream"
msgstr ""

#: glance/api/v1/images.py:729
#, python-format
msgid "Failed to activate image. Got error: %s"
msgstr ""

#: glance/api/v1/images.py:683
msgid "It's invalid to provide multiple image sources."
msgstr ""

#: glance/api/v1/images.py:709
#, python-format
msgid "Provided image size must match the stored image size. (provided size: %(ps)d, stored size: %(ss)d)"
msgstr ""

#: glance/api/v1/images.py:855
msgid "Disk format is not specified."
msgstr ""

#: glance/api/v1/images.py:860
msgid "Container format is not specified."
msgstr ""

#: glance/api/v1/images.py:831
msgid "Forbidden to update deleted image."
msgstr ""

#: glance/api/v1/images.py:978
#, python-format
msgid "Forbidden to modify '%(key)s' of %(status)s image."
msgstr ""

#: glance/api/v1/images.py:987
#, python-format
msgid "Forbidden to modify '%s' of image."
msgstr ""

#: glance/api/v1/images.py:860
msgid "Cannot upload to an unqueued image"
msgstr ""

#: glance/store/__init__.py:469
#, python-format
msgid "Invalid location: %s"
msgstr ""

#: glance/api/v1/images.py:884
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""

#: glance/api/v1/images.py:1069 glance/registry/api/v1/images.py:502
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr ""

#: glance/api/v1/images.py:1076
#, python-format
msgid "Failed to find image to update: %s"
msgstr ""

#: glance/api/v1/images.py:1083
#, python-format
msgid "Forbidden to update image: %s"
msgstr ""

#: glance/api/v1/images.py:1091
msgid "Image operation conflicts"
msgstr ""

#: glance/api/v1/images.py:977
msgid "Image is protected"
msgstr ""

#: glance/api/v1/images.py:984
#, python-format
msgid "Forbidden to delete a %s image."
msgstr ""

#: glance/api/v1/images.py:989
#, python-format
msgid "Image %s not found."
msgstr ""

#: glance/api/v1/images.py:1171
#, python-format
msgid "Failed to find image to delete: %s"
msgstr ""

#: glance/api/v1/images.py:1178
#, python-format
msgid "Forbidden to delete image: %s"
msgstr ""

#: glance/api/v1/images.py:1185 glance/api/v2/images.py:246
#, python-format
msgid "Image %(id)s could not be deleted because it is in use: %(exc)s"
msgstr ""

#: glance/api/v1/images.py:1052 glance/store/__init__.py:231
#, python-format
msgid "Store for scheme %s not found"
msgstr ""

#: glance/api/v1/images.py:1091 glance/api/v1/upload_utils.py:202
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr ""

#: glance/api/v1/members.py:41 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr ""

#: glance/api/v1/members.py:53
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:80
msgid "Unauthorized image access"
msgstr ""

#: glance/api/v1/members.py:117 glance/common/exception.py:287
#, python-format
msgid "The limit has been exceeded on the number of allowed image members for this image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/api/v1/upload_utils.py:115
#, python-format
msgid "Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""

#: glance/api/v1/upload_utils.py:148
#, python-format
msgid "Image %s could not be found after upload. The image may have been deleted during the upload."
msgstr ""

#: glance/api/v1/upload_utils.py:195 glance/api/v2/image_data.py:175
msgid "Error in store configuration. Adding images to store is disabled."
msgstr ""

#: glance/api/v1/upload_utils.py:164
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:256 glance/api/v2/images.py:159
#, python-format
msgid "Denying attempt to upload image because it exceeds the quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:233
msgid "Client disconnected before sending all data to backend"
msgstr ""

#: glance/api/v1/upload_utils.py:241
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:139
#, python-format
msgid "Image %s could not be found after upload. The image may have been deleted during the upload, cleaning up the chunks uploaded."
msgstr ""

#: glance/api/v2/image_data.py:154
#, python-format
msgid "Authentication error - the token may have expired during file upload. Deleting image data for %s."
msgstr ""

#: glance/api/v2/image_data.py:114
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:121
#, python-format
msgid "The incoming image is too large: %s"
msgstr ""

#: glance/api/v2/image_data.py:256
msgid "The requested image has been deactivated. Image data download is forbidden."
msgstr ""

#: glance/api/v2/image_members.py:56
#, python-format
msgid "Error fetching members of image %(image_id)s: %(inner_msg)s"
msgstr ""

#: glance/api/v2/image_members.py:71
#, python-format
msgid "You are not authorized to lookup image %s."
msgstr ""

#: glance/api/v2/image_members.py:80
#, python-format
msgid "%(m_id)s not found in the member list of the image %(i_id)s."
msgstr ""

#: glance/api/v2/image_members.py:86
#, python-format
msgid "You are not authorized to lookup the members of the image %s."
msgstr ""

#: glance/api/v2/image_members.py:119
#, python-format
msgid "Not allowed to create members for image %s."
msgstr ""

#: glance/api/v2/image_members.py:123
#, python-format
msgid "Member %(member_id)s is duplicated for image %(image_id)s"
msgstr ""

#: glance/api/v2/image_members.py:129
#, python-format
msgid "Image member limit exceeded for image %(id)s: %(e)s:"
msgstr ""

#: glance/api/v2/image_members.py:161
#, python-format
msgid "Not allowed to update members for image %s."
msgstr ""

#: glance/api/v2/image_members.py:165
#, python-format
msgid "Incorrect request: %s"
msgstr ""

#: glance/api/v2/image_members.py:197
#, python-format
msgid "Not allowed to list members for image %s."
msgstr ""

#: glance/api/v2/image_members.py:239
#, python-format
msgid "Not allowed to delete members for image %s."
msgstr ""

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr ""

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:269
msgid "Expected a member in the form: {\"member\": \"image_id\"}"
msgstr ""

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr ""

#: glance/api/v2/image_members.py:282
msgid "Expected a status in the form: {\"status\": \"status\"}"
msgstr ""

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr ""

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:644
msgid "An identifier for the image"
msgstr ""

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr ""

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr ""

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr ""

#: glance/api/v2/image_tags.py:56
#, python-format
msgid "Not allowed to update tags for image %s."
msgstr ""

#: glance/api/v2/image_tags.py:60
#, python-format
msgid "Could not update image: %s"
msgstr ""

#: glance/api/v2/image_tags.py:65
#, python-format
msgid "Image tag limit exceeded for image %(id)s: %(e)s:"
msgstr ""

#: glance/api/v2/image_tags.py:85
#, python-format
msgid "Not allowed to delete tags for image %s."
msgstr ""

#: glance/api/v2/images.py:178
msgid "Cannot set locations to empty list."
msgstr ""

#: glance/api/v2/images.py:183
msgid "Owner can't be updated by non admin."
msgstr ""

#: glance/api/v2/images.py:156 glance/api/v2/images.py:184
#, python-format
msgid "Property %s does not exist."
msgstr ""

#: glance/api/v2/images.py:168
#, python-format
msgid "Property %s already present."
msgstr ""

#: glance/api/v2/images.py:179
#, python-format
msgid "Property %s may not be removed."
msgstr ""

#: glance/api/v2/images.py:197
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr ""

#: glance/api/v2/images.py:273
msgid "It's not allowed to update locations if locations are invisible."
msgstr ""

#: glance/api/v2/images.py:291
msgid "It's not allowed to add locations if locations are invisible."
msgstr ""

#: glance/api/v2/images.py:239
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:312
msgid "It's not allowed to remove locations if locations are invisible."
msgstr ""

#: glance/api/v2/images.py:319
msgid "Cannot remove last location in the image."
msgstr ""

#: glance/api/v2/images.py:254
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:295 glance/api/v2/images.py:394
#, python-format
msgid "Attribute '%s' is read-only."
msgstr ""

#: glance/api/v2/images.py:405
#, python-format
msgid "Unable to find `op` in JSON Schema change. It must be one of the following: %(available)s."
msgstr ""

#: glance/api/v2/images.py:410
#, python-format
msgid "Invalid operation: `%(op)s`. It must be one of the following: %(available)s."
msgstr ""

#: glance/api/v2/images.py:327
msgid "Operation objects must contain only one member named \"add\", \"remove\", or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:332
msgid "Operation objects must contain exactly one member named \"add\", \"remove\", or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:319 glance/api/v2/images.py:341
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr ""

#: glance/api/v2/images.py:369
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr ""

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:375
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:378
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:381
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""

#: glance/api/v2/images.py:387
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr ""

#: glance/api/v2/images.py:397
#, python-format
msgid "Attribute '%s' is reserved."
msgstr ""

#: glance/api/v2/images.py:427
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:439
msgid "Unrecognized JSON Schema draft version"
msgstr ""

#: glance/api/v2/images.py:460
msgid "Request body must be a JSON array of operation objects."
msgstr ""

#: glance/api/v2/images.py:465
msgid "Operations must be JSON objects."
msgstr ""

#: glance/api/v2/images.py:487 glance/api/v2/tasks.py:164
#: glance/registry/api/v1/images.py:246
msgid "limit param must be an integer"
msgstr ""

#: glance/api/v2/images.py:491 glance/api/v2/tasks.py:168
#: glance/registry/api/v1/images.py:249
msgid "limit param must be positive"
msgstr ""

#: glance/api/v2/images.py:596
#, python-format
msgid "Invalid sort key: %(sort_key)s. It must be one of the following: %(available)s."
msgstr ""

#: glance/api/v2/images.py:505
#, python-format
msgid "Invalid status: %s"
msgstr ""

#: glance/api/v2/images.py:514
#, python-format
msgid "Invalid visibility value: %s"
msgstr ""

#: glance/api/v2/images.py:626
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr ""

#: glance/api/v2/images.py:645
msgid "Old and new sorting syntax cannot be combined"
msgstr ""

#: glance/api/v2/images.py:676
msgid "Number of sort dirs does not match the number of sort keys"
msgstr ""

#: glance/api/v2/images.py:650
msgid "Descriptive name for the image"
msgstr ""

#: glance/api/v2/images.py:848
msgid "Status of the image"
msgstr ""

#: glance/api/v2/images.py:661
msgid "Scope of image accessibility"
msgstr ""

#: glance/api/v2/images.py:666
msgid "If true, image will not be deletable."
msgstr ""

#: glance/api/v2/images.py:864
msgid "md5 hash of image contents."
msgstr ""

#: glance/api/v2/images.py:675
msgid "Owner of the image"
msgstr ""

#: glance/api/v2/images.py:875
msgid "Size of image file in bytes"
msgstr ""

#: glance/api/v2/images.py:880
msgid "Virtual size of image in bytes"
msgstr ""

#: glance/api/v2/images.py:688
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:693
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:895
msgid "Date and time of image registration"
msgstr ""

#: glance/api/v2/images.py:904
msgid "Date and time of the last image modification"
msgstr ""

#: glance/api/v2/images.py:712
msgid "List of strings related to the image"
msgstr ""

#: glance/api/v2/images.py:919
msgid "URL to access the image file kept in external store"
msgstr ""

#: glance/api/v2/images.py:725
msgid "Amount of ram (in MB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:729
msgid "Amount of disk space (in GB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:934
msgid "An image self url"
msgstr ""

#: glance/api/v2/images.py:939
msgid "An image file url"
msgstr ""

#: glance/api/v2/images.py:944
msgid "An image schema url"
msgstr ""

#: glance/api/v2/images.py:759
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:675
msgid "The unique namespace text."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:680
msgid "The user friendly name for the namespace. Used by UI if available."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:686
msgid "Provides a user friendly description of the namespace."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:692
msgid "Scope of namespace accessibility."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:697
msgid "If true, namespace will not be deletable."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:701
msgid "Owner of the namespace."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:707
msgid "Date and time of namespace creation"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:713
msgid "Date and time of the last namespace modification"
msgstr ""

#: glance/api/v2/metadef_objects.py:197
msgid "Date and time of object creation"
msgstr ""

#: glance/api/v2/metadef_objects.py:203
msgid "Date and time of the last object modification"
msgstr ""

#: glance/api/v2/metadef_properties.py:94
#, python-format
msgid "Property %(property_name)s does not start with the expected resource type association prefix of '%(prefix)s'."
msgstr ""

#: glance/api/v2/metadef_resource_types.py:131
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:125
#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:204
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:199
msgid "Resource type names should be aligned with Heat resource types whenever possible: http://docs.openstack.org/developer/heat/template_guide/openstack.html"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:212
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:207
msgid "Specifies the prefix to use for the given resource type. Any properties in the namespace should be prefixed with this prefix when being applied to the specified resource type. Must include prefix separator (e.g. a colon :)."
msgstr ""

#: glance/api/v2/metadef_resource_types.py:221
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:216
msgid "Some resource types allow more than one key / value pair per instance.  For example, Cinder allows user and image metadata on volumes. Only the image properties metadata is evaluated by Nova (scheduling or drivers). This property allows a namespace target to remove the ambiguity."
msgstr ""

#: glance/api/v2/metadef_resource_types.py:233
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:228
msgid "Date and time of resource type association"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:239
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:234
msgid "Date and time of the last resource type association modification"
msgstr ""

#: glance/api/v2/metadef_tags.py:198
msgid "Date and time of tag creation"
msgstr ""

#: glance/api/v2/metadef_tags.py:204
msgid "Date and time of the last tag modification"
msgstr ""

#: glance/api/v2/tasks.py:137
msgid "This operation is currently not permitted on Glance Tasks. They are auto deleted after reaching the time based on their expires_at property."
msgstr ""

#: glance/api/v2/tasks.py:143
#, python-format
msgid "Invalid status value: %s"
msgstr ""

#: glance/api/v2/tasks.py:149
#, python-format
msgid "Invalid type value: %s"
msgstr ""

#: glance/api/v2/tasks.py:156 glance/registry/api/v1/images.py:258
msgid "Invalid marker format"
msgstr ""

#: glance/api/v2/tasks.py:177
#, python-format
msgid "Task '%s' is required"
msgstr ""

#: glance/api/v2/tasks.py:292
msgid "An identifier for the task"
msgstr ""

#: glance/api/v2/tasks.py:293
msgid "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$"
msgstr ""

#: glance/api/v2/tasks.py:298
msgid "The type of task represented by this content"
msgstr ""

#: glance/api/v2/tasks.py:305
msgid "The current status of this task"
msgstr ""

#: glance/api/v2/tasks.py:315
msgid "The parameters required by task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:319
msgid "The result of current task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:323
msgid "An identifier for the owner of this task"
msgstr ""

#: glance/api/v2/tasks.py:327
msgid "Human-readable informative message only included when appropriate (usually on failure)"
msgstr ""

#: glance/api/v2/tasks.py:332
msgid "Datetime when this resource would be subject to removal"
msgstr ""

#: glance/api/v2/tasks.py:337
msgid "Datetime when this resource was created"
msgstr ""

#: glance/api/v2/tasks.py:341
msgid "Datetime when this resource was updated"
msgstr ""

#: glance/async/taskflow_executor.py:40
msgid "The mode in which the engine will run. Can be 'serial' or 'parallel'."
msgstr ""

#: glance/async/taskflow_executor.py:44
msgid "The number of parallel activities executed at the same time by the engine. The value can be greater than one when the engine mode is 'parallel'."
msgstr ""

#: glance/async/taskflow_executor.py:144
msgid "Task failed due to Internal Error"
msgstr ""

#: glance/async/flows/base_import.py:95
#, python-format
msgid "%(task_id)s of %(task_type)s not configured properly. Missing work dir: %(work_dir)s"
msgstr ""

#: glance/async/flows/base_import.py:127
#, python-format
msgid "%(task_id)s of %(task_type)s not configured properly. Could not load the filesystem store"
msgstr ""

#: glance/async/flows/base_import.py:170
#, python-format
msgid "File %(path)s has invalid backing file %(bfile)s, aborting."
msgstr ""

#: glance/async/flows/convert.py:31
msgid "The format to which images will be automatically converted. When using the RBD backend, this should be set to 'raw'"
msgstr ""

#: glance/async/flows/ovf_process.py:112
msgid "OVA extract is limited to admin"
msgstr ""

#: glance/async/flows/ovf_process.py:153
msgid "Could not find OVF file in OVA archive file."
msgstr ""

#: glance/async/flows/ovf_process.py:205
msgid "Currently, OVA packages containing multiple disk are not supported."
msgstr ""

#: glance/async/flows/ovf_process.py:246
msgid "OVF metadata of interest was not specified in ovf-metadata.json config file. Please set \"cim_pasd\" to a list of interested CIM_ProcessorAllocationSettingData properties."
msgstr ""

#: glance/async/flows/ovf_process.py:252
msgid "OVF properties config file \"ovf-metadata.json\" was not found."
msgstr ""

#: glance/cmd/__init__.py:41
#, python-format
msgid "It appears that the eventlet module has been imported prior to setting %s='yes'. It is currently necessary to disable eventlet.greendns if using ipv6 since eventlet.greendns currently breaks with ipv6 addresses. Please ensure that eventlet is not imported prior to this being set."
msgstr ""

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr ""

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""

#: glance/cmd/control.py:164
#, python-format
msgid "%(verb)sing %(serv)s with %(conf)s"
msgstr ""

#: glance/cmd/control.py:161
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr ""

#: glance/cmd/control.py:176
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr ""

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr ""

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr ""

#: glance/cmd/control.py:225
#, python-format
msgid "Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""

#: glance/cmd/control.py:246
#, python-format
msgid "Reload of %(serv)s not supported"
msgstr ""

#: glance/cmd/control.py:254
#, python-format
msgid "Server %(serv)s is stopped"
msgstr ""

#: glance/cmd/control.py:259
#, python-format
msgid "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr ""

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr ""

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr ""

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr ""

#: glance/cmd/control.py:372
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr ""

#: glance/cmd/manage.py:163
#, python-format
msgid "Invalid int value for age_in_days: %(age_in_days)s"
msgstr ""

#: glance/cmd/manage.py:169
#, python-format
msgid "Invalid int value for max_rows: %(max_rows)s"
msgstr ""

#: glance/cmd/manage.py:173
msgid "Must supply a positive, non-zero value for age."
msgstr ""

#: glance/cmd/manage.py:175
msgid "Maximal age is count of days since epoch."
msgstr ""

#: glance/cmd/manage.py:177
msgid "Minimal rows limit is 1."
msgstr ""

#: glance/cmd/manage.py:330
msgid "Available categories:"
msgstr ""

#: glance/cmd/manage.py:332
#, python-format
msgid "\t%s"
msgstr ""

#: glance/cmd/replicator.py:55
#, python-format
msgid "The image %s is already present on the slave, but our check for it did not find it. This indicates that we do not have permissions to see all the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:282 glance/cmd/replicator.py:319
#: glance/cmd/replicator.py:404 glance/cmd/replicator.py:483
#: glance/cmd/replicator.py:560
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:303
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr ""

#: glance/cmd/replicator.py:717
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance/common/client.py:240
msgid "You have selected to use SSL in connecting, and you have supplied a cert, however you have failed to supply either a key_file parameter or set the GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""

#: glance/common/client.py:248
msgid "You have selected to use SSL in connecting, and you have supplied a key, however you have failed to supply either a cert_file parameter or set the GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""

#: glance/common/client.py:257
#, python-format
msgid "The key file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:264
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:271
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:410
#, python-format
msgid "Constructed URL: %s"
msgstr ""

#: glance/common/config.py:34
msgid "Partial name of a pipeline in your paste configuration file with the service name removed. For example, if your paste section name is [pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr ""

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance/common/config.py:67
msgid "Specifies which task executor to be used to run the task scripts."
msgstr ""

#: glance/common/config.py:70
msgid "Work dir for asynchronous task operations. The directory set here will be used to operate over images - normally before they are imported in the destination store. When providing work dir, make sure enough space is provided for concurrent tasks to run efficiently without running out of space. A rough estimation can be done by multiplying the number of `max_workers` - or the N of workers running - by an average image size (e.g 500MB). The image size estimation should be done based on the average size in your deployment. Note that depending on the tasks running you may need to multiply this number by some factor depending on what the task does. For example, you may want to double the available size if image conversion is enabled. All this being said, remember these are just estimations and you should do them based on the worst case scenario and be prepared to act in case they were wrong."
msgstr ""

#: glance/common/config.py:67
msgid "Whether to allow users to specify image properties beyond what the image schema provides"
msgstr ""

#: glance/common/config.py:70
msgid "Maximum number of image members per image. Negative values evaluate to unlimited."
msgstr ""

#: glance/common/config.py:73
msgid "Maximum number of properties allowed on an image. Negative values evaluate to unlimited."
msgstr ""

#: glance/common/config.py:76
msgid "Maximum number of tags allowed on an image. Negative values evaluate to unlimited."
msgstr ""

#: glance/common/config.py:79
msgid "Maximum number of locations allowed on an image. Negative values evaluate to unlimited."
msgstr ""

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr ""

#: glance/common/config.py:84
msgid "Default value for the number of items returned by a request if not specified explicitly in the request"
msgstr ""

#: glance/common/config.py:87
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance/common/config.py:90
msgid "Whether to include the backend image storage location in image properties. Revealing storage location can be a security risk, so use this setting with caution!"
msgstr ""

#: glance/common/config.py:119
msgid "Whether to include the backend image locations in image properties. For example, if using the file system store a URL of \"file:///path/to/image\" will be returned to the user in the 'direct_url' meta-data field. Revealing storage location can be a security risk, so use this setting with caution! Setting this to true overrides the show_image_direct_url option."
msgstr ""

#: glance/common/config.py:131
msgid "Maximum size of image a user can upload in bytes. Defaults to 1099511627776 bytes (1 TB).WARNING: this value should only be increased after careful consideration and must be set to a value under 8 EB (9223372036854775808)."
msgstr ""

#: glance/common/config.py:137
msgid "Set a system wide quota for every user. This value is the total capacity that a user can use across all storage systems. A value of 0 means unlimited.Optional unit can be specified for the value. Accepted units are B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, GigaBytes and TeraBytes respectively. If no unit is specified then Bytes is assumed. Note that there should not be any space between value and unit and units are case sensitive."
msgstr ""

#: glance/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:111
msgid "Deploy the v1 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:113
msgid "Deploy the v2 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:115
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance/common/config.py:118
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance/common/config.py:161
msgid "AES key for encrypting store 'location' metadata. This includes, if used, Swift or S3 credentials. Should be set to a random string of length 16, 24 or 32 bytes"
msgstr ""

#: glance/common/config.py:166
msgid "Digest algorithm which will be used for digital signature. Use the command \"openssl list-message-digest-algorithms\" to get the available algorithms supported by the version of OpenSSL on the platform. Examples are \"sha1\", \"sha256\", \"sha512\", etc."
msgstr ""

#: glance/common/config.py:179
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr ""

#: glance/common/config.py:218
#, python-format
msgid "Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr ""

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance/common/exception.py:67
#, python-format
msgid "Incorrect auth strategy, expected \"%(expected)s\" but received \"%(received)s\""
msgstr ""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr ""

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr ""

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr ""

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance/common/exception.py:97
#, python-format
msgid "The size of the data %(image_size)s will exceed the limit. %(remaining)s bytes remaining."
msgstr ""

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr ""

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr ""

#: glance/common/exception.py:112
#, python-format
msgid "Image upload problem: %s"
msgstr ""

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr ""

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:128
#, python-format
msgid "Metadata definition namespace %(namespace)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:133
#, python-format
msgid "Metadata definition property %(property_name)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:138
#, python-format
msgid "Metadata definition object %(object_name)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:143
#, python-format
msgid "Metadata definition resource-type-association %(resource_type)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:148
#, python-format
msgid "Metadata definition resource-type %(resource_type_name)s is a seeded-system type and cannot be deleted."
msgstr ""

#: glance/common/exception.py:153
#, python-format
msgid "Metadata definition tag %(tag_name)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr ""

#: glance/common/exception.py:138
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr ""

#: glance/common/exception.py:166
msgid "Sort direction supplied was not valid."
msgstr ""

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:174
msgid "Invalid configuration in glance-swift conf file."
msgstr ""

#: glance/common/exception.py:178
msgid "Unable to filter using the specified operator."
msgstr ""

#: glance/common/exception.py:146
msgid "Unable to filter using the specified range."
msgstr ""

#: glance/common/exception.py:186
#, python-format
msgid "Invalid value for option %(option)s: %(value)s"
msgstr ""

#: glance/common/exception.py:150
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: glance/common/exception.py:158
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance/common/exception.py:162
msgid "There was an error connecting to a server"
msgstr ""

#: glance/common/exception.py:166
msgid "There was an error configuring the client."
msgstr ""

#: glance/common/exception.py:170
#, python-format
msgid "The request returned a 302 Multiple Choices. This generally means that you have not included a version indicator in a request URI.\n\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:176
#, python-format
msgid "The request returned a 413 Request Entity Too Large. This generally means that rate limiting or a quota threshold was breached.\n\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:227
msgid "The request returned 503 Service Unavailable. This generally occurs on service overload or other transient outage."
msgstr ""

#: glance/common/exception.py:198
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: glance/common/exception.py:202
#, python-format
msgid "The request returned an unexpected status: %(status)s.\n\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:207
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: glance/common/exception.py:211
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:221
#, python-format
msgid "Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:243
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance/common/exception.py:247
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance/common/exception.py:251
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance/common/exception.py:255
#, python-format
msgid "Multiple 'image' service matches for region %(region)s. This generally means that a region is required and you have not supplied one."
msgstr ""

#: glance/common/exception.py:261
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance/common/exception.py:265
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance/common/exception.py:269
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance/common/exception.py:283
msgid "The provided image is too large."
msgstr ""

#: glance/common/exception.py:293
#, python-format
msgid "The limit has been exceeded on the number of allowed image properties. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:298
#, python-format
msgid "The limit has been exceeded on the number of allowed image tags. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:303
#, python-format
msgid "The limit has been exceeded on the number of allowed image locations. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:317
msgid "System SIGHUP signal received."
msgstr ""

#: glance/common/exception.py:308
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:312
msgid "An unknown task exception occurred"
msgstr ""

#: glance/common/exception.py:329
msgid "Task was not configured properly"
msgstr ""

#: glance/common/exception.py:333
#, python-format
msgid "Image with the given id %(image_id)s was not found"
msgstr ""

#: glance/common/exception.py:316
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/exception.py:320
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr ""

#: glance/common/exception.py:324
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr ""

#: glance/common/exception.py:328
#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:354
msgid "An import task exception occurred"
msgstr ""

#: glance/common/exception.py:333
#, python-format
msgid "The location %(location)s already exists"
msgstr ""

#: glance/common/exception.py:341
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance/common/exception.py:346
#, python-format
msgid "Image status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:372
#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr ""

#: glance/common/exception.py:377
#, python-format
msgid "A metadata definition object with name=%(object_name)s already exists in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:382
#, python-format
msgid "A metadata definition property with name=%(property_name)s already exists in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:387
#, python-format
msgid "A metadata definition resource-type with name=%(resource_type_name)s already exists."
msgstr ""

#: glance/common/exception.py:392
#, python-format
msgid "The metadata definition resource-type association of resource-type=%(resource_type_name)s to namespace=%(namespace_name)s already exists."
msgstr ""

#: glance/common/exception.py:399
#, python-format
msgid "A metadata tag with name=%(name)s already exists in namespace=%(namespace_name)s. (Please note that metadata tag names are case insensitive)."
msgstr ""

#: glance/common/exception.py:410
#, python-format
msgid "The metadata definition %(record_type)s with name=%(record_name)s not deleted. Other records still refer to it."
msgstr ""

#: glance/common/exception.py:416
#, python-format
msgid "Metadata definition namespace=%(namespace_name)s was not found."
msgstr ""

#: glance/common/exception.py:421
#, python-format
msgid "The metadata definition object with name=%(object_name)s was not found in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:427
#, python-format
msgid "The metadata definition property with name=%(property_name)s was not found in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:433
#, python-format
msgid "The metadata definition resource-type with name=%(resource_type_name)s, was not found."
msgstr ""

#: glance/common/exception.py:438
#, python-format
msgid "The metadata definition resource-type association of resource-type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found."
msgstr ""

#: glance/common/exception.py:445
#, python-format
msgid "The metadata definition tag with name=%(name)s was not found in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:451
#, python-format
msgid "Unable to verify signature: %(reason)s"
msgstr ""

#: glance/common/exception.py:455
#, python-format
msgid "Version is invalid: %(reason)s"
msgstr ""

#: glance/common/exception.py:459
msgid "Invalid property definition"
msgstr ""

#: glance/common/exception.py:463
msgid "Invalid type definition"
msgstr ""

#: glance/common/exception.py:467
#, python-format
msgid "Property '%(name)s' may not have value '%(val)s': %(msg)s"
msgstr ""

#: glance/common/exception.py:477
#, python-format
msgid "Artifact with id=%(id)s was not found"
msgstr ""

#: glance/common/exception.py:481
#, python-format
msgid "Artifact with id=%(id)s is not accessible"
msgstr ""

#: glance/common/exception.py:485
msgid "Artifact with the specified type, name and version already exists"
msgstr ""

#: glance/common/exception.py:490
#, python-format
msgid "Artifact cannot change state from %(source)s to %(target)s"
msgstr ""

#: glance/common/exception.py:494
#, python-format
msgid "Artifact with the specified type, name and version already has the direct dependency=%(dep)s"
msgstr ""

#: glance/common/exception.py:499
#, python-format
msgid "Artifact with the specified type, name and version already has the transitive dependency=%(dep)s"
msgstr ""

#: glance/common/exception.py:504
msgid "Artifact with a circular dependency can not be created"
msgstr ""

#: glance/common/exception.py:508
#, python-format
msgid "Operator %(op)s is not supported"
msgstr ""

#: glance/common/exception.py:512
#, python-format
msgid "Show level %(shl)s is not supported in this operation"
msgstr ""

#: glance/common/exception.py:516
#, python-format
msgid "Property's %(prop)s value has not been found"
msgstr ""

#: glance/common/exception.py:520
#, python-format
msgid "Artifact has no property %(prop)s"
msgstr ""

#: glance/common/exception.py:524
#, python-format
msgid "Cannot use this parameter with the operator %(op)s"
msgstr ""

#: glance/common/exception.py:528
#, python-format
msgid "Cannot load artifact '%(name)s'"
msgstr ""

#: glance/common/exception.py:532
#, python-format
msgid "Plugin name '%(plugin)s' should match artifact typename '%(name)s'"
msgstr ""

#: glance/common/exception.py:537
#, python-format
msgid "No plugin for '%(name)s' has been loaded"
msgstr ""

#: glance/common/exception.py:541
#, python-format
msgid "Artifact type with name '%(name)s' and version '%(version)s' is not known"
msgstr ""

#: glance/common/exception.py:546
#, python-format
msgid "Artifact state cannot be changed from %(curr)s to %(to)s"
msgstr ""

#: glance/common/exception.py:550
msgid "Invalid jsonpatch request"
msgstr ""

#: glance/common/exception.py:554
#, python-format
msgid "The provided body %(body)s is invalid under given schema: %(schema)s"
msgstr ""

#: glance/common/exception.py:559
#, python-format
msgid "The provided path '%(path)s' is invalid: %(explanation)s"
msgstr ""

#: glance/common/jsonpatchvalidator.py:103
msgid "Json path should start with a '/', end with no '/', no 2 subsequent '/' are allowed."
msgstr ""

#: glance/common/jsonpatchvalidator.py:107
msgid "Pointer contains '~' which is not part of a recognized escape sequence [~0, ~1]."
msgstr ""

#: glance/common/property_utils.py:31
msgid "The location of the property protection file.This file contains the rules for property protections and the roles/policies associated with it. If this config value is not specified, by default, property protections won't be enforced. If a value is specified and the file is not found, then the glance-api service will not start."
msgstr ""

#: glance/common/property_utils.py:40
msgid "This config value indicates whether \"roles\" or \"policies\" are used in the property protection file."
msgstr ""

#: glance/common/property_utils.py:127
#, python-format
msgid "Property protection on operation %(operation)s for rule %(rule)s is not found. No role will be allowed to perform this operation."
msgstr ""

#: glance/common/rpc.py:139
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:144
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:151
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:160
msgid "Command not found"
msgstr ""

#: glance/common/semver_db.py:77
#, python-format
msgid "Version component is too large (%d max)"
msgstr ""

#: glance/common/semver_db.py:125
#, python-format
msgid "Prerelease numeric component is too large (%d characters max)"
msgstr ""

#: glance/common/signature_utils.py:138
#, python-format
msgid "Invalid signature key type: %s"
msgstr ""

#: glance/common/signature_utils.py:161
#, python-format
msgid "Invalid mask_gen_algorithm: %s"
msgstr ""

#: glance/common/signature_utils.py:174
#, python-format
msgid "Invalid pss_salt_length: %s"
msgstr ""

#: glance/common/signature_utils.py:261 glance/common/signature_utils.py:335
msgid "Required image properties for signature verification do not exist. Cannot verify signature."
msgstr ""

#: glance/common/signature_utils.py:285 glance/common/signature_utils.py:361
msgid "Unable to verify signature since the algorithm is unsupported on this system"
msgstr ""

#: glance/common/signature_utils.py:294
msgid "Error occurred while creating the verifier"
msgstr ""

#: glance/common/signature_utils.py:373
msgid "Signature verification failed."
msgstr ""

#: glance/common/signature_utils.py:378
msgid "Error occurred while verifying the signature"
msgstr ""

#: glance/common/signature_utils.py:394
msgid "The signature data was not properly encoded using base64"
msgstr ""

#: glance/common/signature_utils.py:410
#, python-format
msgid "Invalid signature hash method: %s"
msgstr ""

#: glance/common/signature_utils.py:436
#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr ""

#: glance/common/signature_utils.py:467
#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr ""

#: glance/common/signature_utils.py:473
#, python-format
msgid "Invalid certificate format: %s"
msgstr ""

#: glance/common/signature_utils.py:483
#, python-format
msgid "Certificate format not supported: %s"
msgstr ""

#: glance/common/signature_utils.py:505
#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr ""

#: glance/common/signature_utils.py:510
#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr ""

#: glance/common/swift_store_utils.py:25
msgid "The reference to the default swift account/backing store parameters to use for adding new images."
msgstr ""

#: glance/common/swift_store_utils.py:28
msgid "The address where the Swift authentication service is listening.(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:31
msgid "The user to authenticate against the Swift authentication service (deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:34
msgid "Auth key for the user authenticating against the Swift authentication service. (deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:37
msgid "The config file that has the swift account(s)configs."
msgstr ""

#: glance/common/utils.py:251
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:261
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr ""

#: glance/common/utils.py:313
msgid "Cannot be a negative value."
msgstr ""

#: glance/common/utils.py:509
#, python-format
msgid "There is a problem with your %(error_key_name)s %(error_filename)s.  Please verify it.  Error: %(ioe)s"
msgstr ""

#: glance/common/utils.py:516
#, python-format
msgid "There is a problem with your %(error_key_name)s %(error_filename)s.  Please verify it. OpenSSL error: %(ce)s"
msgstr ""

#: glance/common/utils.py:530
#, python-format
msgid "There is a problem with your key pair.  Please verify that cert %(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""

#: glance/common/utils.py:480
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:483
#, python-format
msgid "Port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:492
#, python-format
msgid "Host \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:495
#, python-format
msgid "%s Please specify a host:port pair, where host is an IPv4 address, IPv6 address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""

#: glance/common/utils.py:530
msgid "Property names can't contain 4 byte unicode."
msgstr ""

#: glance/common/utils.py:533
#, python-format
msgid "%s can't contain 4 byte unicode characters."
msgstr ""

#: glance/common/utils.py:542
msgid "Param values can't contain 4 byte unicode."
msgstr ""

#: glance/common/utils.py:562
#, python-format
msgid "Value %(value)d out of range, must not exceed %(max)d"
msgstr ""

#: glance/common/utils.py:570
#, python-format
msgid "'%(param)s' value out of range, must not exceed %(max)d"
msgstr ""

#: glance/common/utils.py:627
#, python-format
msgid "Invalid filter value %s. There is no comma before opening quotation mark."
msgstr ""

#: glance/common/utils.py:632
#, python-format
msgid "Invalid filter value %s. There is no comma after closing quotation mark."
msgstr ""

#: glance/common/utils.py:637
#, python-format
msgid "Invalid filter value %s. The quote is not closed."
msgstr ""

#: glance/common/utils.py:687
msgid "Unable to filter on a unknown operator."
msgstr ""

#: glance/common/wsgi.py:53
msgid "Address to bind the server.  Useful when selecting a particular network interface."
msgstr ""

#: glance/common/wsgi.py:56
msgid "The port on which the server will listen."
msgstr ""

#: glance/common/wsgi.py:61
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr ""

#: glance/common/wsgi.py:64
msgid "The value for the socket option TCP_KEEPIDLE.  This is the time in seconds that the connection must be idle before TCP starts sending keepalive probes."
msgstr ""

#: glance/common/wsgi.py:67
msgid "CA certificate file to use to verify connecting clients."
msgstr ""

#: glance/common/wsgi.py:69
msgid "Certificate file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:71
msgid "Private key file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:83
msgid "The number of child process workers that will be created to service requests. The default will be equal to the number of CPUs available."
msgstr ""

#: glance/common/wsgi.py:85
msgid "Maximum line size of message headers to be accepted. max_header_line may need to be increased when using large tokens (typically those generated by the Keystone v3 API with big service catalogs"
msgstr ""

#: glance/common/wsgi.py:92
msgid "If False, server will return the header \"Connection: close\", If True, server will return \"Connection: Keep-Alive\" in its responses. In order to close the client socket connection explicitly after the response is sent and read successfully by the client, you simply have to set this option to False when you create a wsgi server."
msgstr ""

#: glance/common/wsgi.py:101
msgid "Timeout for client connections' socket operations. If an incoming connection is idle for this number of seconds it will be closed. A value of '0' means wait forever."
msgstr ""

#: glance/common/wsgi.py:109
msgid "The HTTP header used to determine the scheme for the original request, even if it was removed by an SSL terminating proxy. Typical value is \"HTTP_X_FORWARDED_PROTO\"."
msgstr ""

#: glance/common/wsgi.py:117
msgid "If False fully disable profiling feature."
msgstr ""

#: glance/common/wsgi.py:119
msgid "If False doesn't trace SQL requests."
msgstr ""

#: glance/common/wsgi.py:121
msgid "Secret key to use to sign Glance API and Glance Registry services tracing messages."
msgstr ""

#: glance/common/wsgi.py:131
msgid "When running server in SSL mode, you must specify both a cert_file and key_file option value in your configuration file"
msgstr ""

#: glance/common/wsgi.py:169
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: glance/common/wsgi.py:233
msgid "eventlet 'poll' nor 'selects' hubs are available on this platform"
msgstr ""

#: glance/common/wsgi.py:786
#, python-format
msgid "Malformed Content-Range header: %s"
msgstr ""

#: glance/common/wsgi.py:819
msgid "Unexpected body type. Expected list/dict."
msgstr ""

#: glance/common/wsgi.py:552
msgid "Malformed JSON in request body."
msgstr ""

#: glance/common/wsgi.py:912
msgid "A body is not expected with this request."
msgstr ""

#: glance/common/wsgi.py:924
msgid "Error decoding your request. Either the URL or the request body contained characters that could not be decoded by Glance"
msgstr ""

#: glance/common/glare/declarative.py:59
msgid "Not a valid value type"
msgstr ""

#: glance/common/glare/declarative.py:92
msgid "Default value is invalid"
msgstr ""

#: glance/common/glare/declarative.py:106
#: glance/common/glare/declarative.py:712
msgid "Value is required"
msgstr ""

#: glance/common/glare/declarative.py:129
msgid "Invalid item type specification"
msgstr ""

#: glance/common/glare/declarative.py:132
msgid "List definitions may hot have defaults"
msgstr ""

#: glance/common/glare/declarative.py:147
msgid "Cannot specify 'min_size' explicitly"
msgstr ""

#: glance/common/glare/declarative.py:152
msgid "Cannot specify 'max_size' explicitly"
msgstr ""

#: glance/common/glare/declarative.py:177
msgid "List size is less than minimum"
msgstr ""

#: glance/common/glare/declarative.py:186
msgid "List size is greater than maximum"
msgstr ""

#: glance/common/glare/declarative.py:201
msgid "Items have to be unique"
msgstr ""

#: glance/common/glare/declarative.py:249
msgid "Invalid dict property type specification"
msgstr ""

#: glance/common/glare/declarative.py:255
msgid "Invalid dict property type"
msgstr ""

#: glance/common/glare/declarative.py:269
msgid "Dictionary contains unexpected key(s)"
msgstr ""

#: glance/common/glare/declarative.py:285
msgid "Dictionary size is less than minimum"
msgstr ""

#: glance/common/glare/declarative.py:295
msgid "Dictionary size is greater than maximum"
msgstr ""

#: glance/common/glare/declarative.py:362
msgid "Custom validators list should contain tuples '(function, message)'"
msgstr ""

#: glance/common/glare/declarative.py:379
#, python-format
msgid "Allowed values %s are invalid under given validators"
msgstr ""

#: glance/common/glare/declarative.py:386
msgid "Is not allowed value"
msgstr ""

#: glance/common/glare/declarative.py:404
msgid "Dependency relations cannot be mutable"
msgstr ""

#: glance/common/glare/declarative.py:463
msgid "Attempt to set readonly property"
msgstr ""

#: glance/common/glare/declarative.py:471
msgid "Attempt to set value of immutable property"
msgstr ""

#: glance/common/glare/declarative.py:557
msgid "Type version has to be a valid semver string"
msgstr ""

#: glance/common/glare/declarative.py:565
#, python-format
msgid "%(attribute)s is required"
msgstr ""

#: glance/common/glare/declarative.py:570
#, python-format
msgid "%(attribute)s have to be string"
msgstr ""

#: glance/common/glare/declarative.py:573
#, python-format
msgid "%(attribute)s may not be longer than %(length)i"
msgstr ""

#: glance/common/glare/declarative.py:577
#, python-format
msgid "%(attribute)s may not be shorter than %(length)i"
msgstr ""

#: glance/common/glare/declarative.py:581
#, python-format
msgid "%(attribute)s should match pattern %(pattern)s"
msgstr ""

#: glance/common/glare/declarative.py:625
msgid "Cannot declare artifact property with reserved name 'metadata'"
msgstr ""

#: glance/common/glare/declarative.py:654
msgid "Unable to modify collection in immutable or readonly property"
msgstr ""

#: glance/common/glare/definitions.py:71
msgid "Max string length may not exceed 255 characters"
msgstr ""

#: glance/common/glare/definitions.py:74
msgid "Length  is greater than maximum"
msgstr ""

#: glance/common/glare/definitions.py:85
msgid "Min string length may not be negative"
msgstr ""

#: glance/common/glare/definitions.py:89
msgid "Length is less than minimum"
msgstr ""

#: glance/common/glare/definitions.py:101
msgid "Does not match pattern"
msgstr ""

#: glance/common/glare/definitions.py:158
#: glance/common/glare/definitions.py:210
#: glance/common/glare/definitions.py:260
msgid "Value is less than minimum"
msgstr ""

#: glance/common/glare/definitions.py:169
#: glance/common/glare/definitions.py:221
#: glance/common/glare/definitions.py:271
msgid "Value is greater than maximum"
msgstr ""

#: glance/common/glare/definitions.py:312
msgid "Array property can't have item_type=Array"
msgstr ""

#: glance/common/glare/definitions.py:384
msgid "Unable to specify artifact type explicitly"
msgstr ""

#: glance/common/glare/definitions.py:387
msgid "Unable to specify artifact type version explicitly"
msgstr ""

#: glance/common/glare/definitions.py:426
msgid "Unable to specify version if multiple types are possible"
msgstr ""

#: glance/common/glare/definitions.py:441
msgid "Invalid referenced type"
msgstr ""

#: glance/common/glare/definitions.py:444
msgid "Unable to specify version if type is not specified"
msgstr ""

#: glance/common/glare/definitions.py:462
msgid "Invalid reference list specification"
msgstr ""

#: glance/common/glare/definitions.py:522
msgid "BinaryObject property cannot be declared mutable"
msgstr ""

#: glance/common/glare/definitions.py:532
msgid "Blob size is not set"
msgstr ""

#: glance/common/glare/definitions.py:536
msgid "File too large"
msgstr ""

#: glance/common/glare/definitions.py:540
msgid "File too small"
msgstr ""

#: glance/common/glare/definitions.py:545
msgid "Too few locations"
msgstr ""

#: glance/common/glare/definitions.py:550
msgid "Too many locations"
msgstr ""

#: glance/common/glare/loader.py:31
msgid "When false, no artifacts can be loaded regardless of available_plugins. When true, artifacts can be loaded."
msgstr ""

#: glance/common/glare/loader.py:35
msgid "A list of artifacts that are allowed in the format name or name-version. Empty list means that any artifact can be loaded."
msgstr ""

#: glance/common/glare/serialization.py:192
#, python-format
msgid "Blob %(name)s may not have multiple values"
msgstr ""

#: glance/common/glare/serialization.py:213
#, python-format
msgid "Relation %(name)s may not have multiple values"
msgstr ""

#: glance/common/location_strategy/__init__.py:25
msgid "This value sets what strategy will be used to determine the image location order. Currently two strategies are packaged with Glance 'location_order' and 'store_type'."
msgstr ""

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid "%(strategy)s is registered as a module twice. %(module)s is not being used."
msgstr ""

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid "Invalid location_strategy option: %(name)s. The valid strategy option(s) is(are): %(strategies)s"
msgstr ""

#: glance/common/location_strategy/store_type.py:28
msgid "The store names to use to get store preference order. The name must be registered by one of the stores defined by the 'stores' config option. This option will be applied when you using 'store_type' option as image location strategy defined by the 'location_strategy' config option."
msgstr ""

#: glance/common/scripts/utils.py:61
#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr ""

#: glance/common/scripts/utils.py:95
msgid "File based imports are not allowed. Please use a non-local source of image data."
msgstr ""

#: glance/common/scripts/utils.py:104
#, python-format
msgid "The given uri is not valid. Please specify a valid uri from the following list of supported uri %(supported)s"
msgstr ""

#: glance/common/scripts/image_import/main.py:103
#, python-format
msgid "The Image %(image_id)s object being created by this task %(task_id)s, is no longer in valid status for further processing."
msgstr ""

#: glance/contrib/plugins/image_artifact/v2/image.py:44
msgid "Either a file or a legacy_image_id has to be specified"
msgstr ""

#: glance/contrib/plugins/image_artifact/v2/image.py:49
msgid "Both file and legacy_image_id may not be specified at the same time"
msgstr ""

#: glance/contrib/plugins/image_artifact/v2/image.py:59
msgid "Glance client not installed"
msgstr ""

#: glance/contrib/plugins/image_artifact/v2/image.py:68
msgid "Unable to get legacy image"
msgstr ""

#: glance/contrib/plugins/image_artifact/v2/image.py:82
msgid "Legacy image was not found"
msgstr ""

#: glance/db/__init__.py:85 glance/db/__init__.py:127 glance/db/__init__.py:137
#: glance/db/__init__.py:151
#, python-format
msgid "No artifact found with ID %s"
msgstr ""

#: glance/db/__init__.py:64 glance/db/__init__.py:167 glance/db/__init__.py:179
#: glance/db/sqlalchemy/api.py:181
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:238
#, python-format
msgid "The target member %(member_id)s is already associated with image %(image_id)s."
msgstr ""

#: glance/db/__init__.py:255
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/__init__.py:334 glance/db/__init__.py:360
#: glance/db/__init__.py:377 glance/db/simple/api.py:762
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/__init__.py:539
#, python-format
msgid "Could not find namespace %s"
msgstr ""

#: glance/db/__init__.py:561 glance/db/__init__.py:571
#: glance/db/__init__.py:581 glance/db/__init__.py:591
#, python-format
msgid "The specified namespace %s could not be found"
msgstr ""

#: glance/db/__init__.py:682
#, python-format
msgid "Could not find metadata object %s"
msgstr ""

#: glance/db/__init__.py:705
#, python-format
msgid "The specified metadata object %s could not be found"
msgstr ""

#: glance/db/__init__.py:798
#, python-format
msgid "The specified resource type %s could not be found "
msgstr ""

#: glance/db/__init__.py:845
#, python-format
msgid "Could not find property %s"
msgstr ""

#: glance/db/__init__.py:867
#, python-format
msgid "The specified property %s could not be found"
msgstr ""

#: glance/db/__init__.py:931
#, python-format
msgid "Could not find metadata tag %s"
msgstr ""

#: glance/db/__init__.py:957
#, python-format
msgid "The specified metadata tag %s could not be found"
msgstr ""

#: glance/db/simple/api.py:256 glance/db/sqlalchemy/api.py:407
msgid "Unable to filter on a range with a non-numeric value."
msgstr ""

#: glance/db/simple/api.py:317 glance/db/sqlalchemy/api.py:525
#, python-format
msgid "Unable to filter by unknown operator '%s'."
msgstr ""

#: glance/db/simple/api.py:425 glance/db/sqlalchemy/api.py:951
msgid "Image id is required."
msgstr ""

#: glance/db/simple/api.py:570 glance/db/sqlalchemy/api.py:873
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr ""

#: glance/db/simple/api.py:590 glance/db/simple/api.py:616
#: glance/db/sqlalchemy/api.py:893 glance/db/sqlalchemy/api.py:919
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr ""

#: glance/db/simple/api.py:600
msgid "The status of deleted image location can only be set to 'pending_delete' or 'deleted'."
msgstr ""

#: glance/db/simple/api.py:772 glance/db/sqlalchemy/api.py:1256
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr ""

#: glance/db/simple/api.py:890
msgid "Task does not exist"
msgstr ""

#: glance/db/simple/api.py:1155
#: glance/db/sqlalchemy/metadef_api/namespace.py:249
#, python-format
msgid "Invalid update. It would result in a duplicate metadata definition namespace with the same name of %s"
msgstr ""

#: glance/db/simple/api.py:1176
#: glance/db/sqlalchemy/metadef_api/namespace.py:88
#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr ""

#: glance/db/simple/api.py:1184 glance/db/simple/api.py:2128
#: glance/db/sqlalchemy/metadef_api/namespace.py:97
#: glance/db/sqlalchemy/metadef_api/namespace.py:119
#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr ""

#: glance/db/simple/api.py:1307 glance/db/sqlalchemy/metadef_api/object.py:35
#, python-format
msgid "Metadata definition object not found for id=%s"
msgstr ""

#: glance/db/simple/api.py:1388
#, python-format
msgid "Invalid update. It would result in a duplicate metadata definition object with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/simple/api.py:1515
#: glance/db/sqlalchemy/metadef_api/property.py:122
#, python-format
msgid "Invalid update. It would result in a duplicate metadata definition property with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/simple/api.py:1559 glance/db/sqlalchemy/metadef_api/property.py:37
#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr ""

#: glance/db/simple/api.py:1765
#, python-format
msgid "Metadata definition tag not found for id=%s"
msgstr ""

#: glance/db/sqlalchemy/api.py:85
msgid "You do not own this image"
msgstr ""

#: glance/db/sqlalchemy/api.py:337
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/api.py:507
#, python-format
msgid "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."
msgstr ""

#: glance/db/sqlalchemy/api.py:682
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid "cannot transition from %(current)s to %(next)s in update (wanted from_state=%(from)s)"
msgstr ""

#: glance/db/sqlalchemy/api.py:902
msgid "The status of deleted image location can only be set to 'pending_delete' or 'deleted'"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:42
msgid "Path to the directory where json metadata files are stored"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/object.py:112
#, python-format
msgid "Invalid update. It would result in a duplicate metadata definition object with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:86
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:149
msgid "URI cannot contain more than one occurrence of a scheme.If you have specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, you need to change it to use the swift+http:// scheme, like so: swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:123
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:185
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:135
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:246
msgid "Badly formed credentials in Swift URI."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:152
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:214
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr ""

#: glance/domain/__init__.py:59
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr ""

#: glance/domain/__init__.py:129
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr ""

#: glance/domain/__init__.py:151
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:154
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:171
msgid "Visibility must be either \"public\" or \"private\""
msgstr ""

#: glance/domain/__init__.py:190
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:202
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:214 glance/domain/__init__.py:227
msgid "Cannot be a negative value"
msgstr ""

#: glance/domain/__init__.py:255
#, python-format
msgid "Not allowed to deactivate image in status '%s'"
msgstr ""

#: glance/domain/__init__.py:268
#, python-format
msgid "Not allowed to reactivate image in status '%s'"
msgstr ""

#: glance/domain/__init__.py:292
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr ""

#: glance/glare/dependency.py:66
#, python-format
msgid "Not all dependencies are in '%s' state"
msgstr ""

#: glance/glare/dependency.py:98
#, python-format
msgid "Dependency property '%s' has to be deleted first"
msgstr ""

#: glance/glare/location.py:159
#, python-format
msgid "Get blob %(name)s data failed: %(err)s."
msgstr ""

#: glance/glare/updater.py:52
msgid "No property to access"
msgstr ""

#: glance/glare/updater.py:130
#, python-format
msgid "Array has no element at position %d"
msgstr ""

#: glance/glare/updater.py:134
#, python-format
msgid "Not an array idx '%s'"
msgstr ""

#: glance/glare/updater.py:174
#, python-format
msgid "No such key '%s' in a dict"
msgstr ""

#: glance/image_cache/__init__.py:34
msgid "The driver to use for image cache management."
msgstr ""

#: glance/image_cache/__init__.py:39
msgid "The upper limit (the maximum size of accumulated cache in bytes) beyond which the cache pruner, if running, starts cleaning the image cache."
msgstr ""

#: glance/image_cache/__init__.py:43
msgid "The amount of time to let an incomplete image remain in the cache, before the cache cleaner, if running, will remove the incomplete image."
msgstr ""

#: glance/image_cache/__init__.py:47
msgid "Base directory that the image cache uses."
msgstr ""

#: glance/image_cache/__init__.py:253
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""

#: glance/image_cache/client.py:117
msgid "--os_auth_url option or OS_AUTH_URL environment variable required when keystone authentication strategy is enabled\n"
msgstr ""

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:39
msgid "The path to the sqlite file database that will be used for image cache management."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:121
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/xattr.py:104
#, python-format
msgid "The device housing the image cache directory %(image_cache_dir)s does not support xattr. It is likely you need to edit your fstab and add the user_xattr option to the appropriate line for the device housing the cache directory."
msgstr ""

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr ""

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr ""

#: glance/registry/api/v1/images.py:107 glance/registry/api/v1/images.py:112
msgid "Invalid marker. Image could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:216
msgid "Unrecognized changes-since value"
msgstr ""

#: glance/registry/api/v1/images.py:221
msgid "protected must be True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:268
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:277
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:303
msgid "is_public must be None, True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:395
msgid "Invalid image id format"
msgstr ""

#: glance/registry/api/v1/images.py:409
#, python-format
msgid "Image with identifier %s already exists!"
msgstr ""

#: glance/registry/api/v1/images.py:451
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr ""

#: glance/registry/api/v1/images.py:322 glance/registry/api/v1/images.py:363
#: glance/registry/api/v1/images.py:466 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr ""

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr ""

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr ""

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr ""

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:20
msgid "The protocol to use for communication with the registry server.  Either http or https."
msgstr ""

#: glance/registry/client/__init__.py:26
msgid "The path to the key file to use in SSL connections to the registry server, if any. Alternately, you may set the GLANCE_CLIENT_KEY_FILE environment variable to a filepath of the key file"
msgstr ""

#: glance/registry/client/__init__.py:31
msgid "The path to the cert file to use in SSL connections to the registry server, if any. Alternately, you may set the GLANCE_CLIENT_CERT_FILE environment variable to a filepath of the CA cert file"
msgstr ""

#: glance/registry/client/__init__.py:36
msgid "The path to the certifying authority cert file to use in SSL connections to the registry server, if any. Alternately, you may set the GLANCE_CLIENT_CA_FILE environment variable to a filepath of the CA cert file."
msgstr ""

#: glance/registry/client/__init__.py:42
msgid "When using SSL in connections to the registry server, do not require validation via a certifying authority. This is the registry's equivalent of specifying --insecure on the command line using glanceclient for the API."
msgstr ""

#: glance/registry/client/__init__.py:36
msgid "The period of time, in seconds, that the API server will wait for a registry request to complete. A value of 0 implies no timeout."
msgstr ""

#: glance/registry/client/__init__.py:64
msgid "Whether to pass through the user token when making requests to the registry. To prevent failures with token expiration during big files upload, it is recommended to set this parameter to False.If \"use_user_token\" is not in effect, then admin credentials can be specified."
msgstr ""

#: glance/registry/client/__init__.py:73
msgid "The administrators user name. If \"use_user_token\" is not in effect, then admin credentials can be specified."
msgstr ""

#: glance/registry/client/__init__.py:78
msgid "The administrators password. If \"use_user_token\" is not in effect, then admin credentials can be specified."
msgstr ""

#: glance/registry/client/__init__.py:83
msgid "The tenant name of the administrative user. If \"use_user_token\" is not in effect, then admin tenant name can be specified."
msgstr ""

#: glance/registry/client/__init__.py:88
msgid "The URL to the keystone service. If \"use_user_token\" is not in effect and using keystone auth, then URL of keystone can be specified."
msgstr ""

#: glance/registry/client/__init__.py:94
msgid "The strategy to use for authentication. If \"use_user_token\" is not in effect, then auth strategy can be specified."
msgstr ""

#: glance/registry/client/__init__.py:99
msgid "The region for the authentication service. If \"use_user_token\" is not in effect and using keystone auth, then region name can be specified."
msgstr ""

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr ""

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr ""

#: glance/tests/unit/test_migrations.py:927
#, python-format
msgid "location: %s data lost"
msgstr ""

