msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2021-07-19 16:42-0500\n"
"PO-Revision-Date: 2024-11-06 10:10\n"
"Last-Translator: \n"
"Language-Team: Belarusian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-11-05 06:53+0000\n"
"X-Generator: Launchpad (build 22ade00ab50b929fac63b8ee7252243aceda294a)\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || n%10>=5 && n%10<=9 || n%100>=11 && n%100<=14 ? 2 : 3);\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: be\n"
"X-Crowdin-File: /main/noble/en_GB/po-apt-listchanges_apt-listchanges-be.po\n"
"X-Crowdin-File-ID: 629\n"
"Language: be_BY\n"

#: ../apt_listchanges/apt_listchanges.py:198
#, python-format
msgid "Unknown frontend: %s"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:214
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:335
#, python-format
msgid "News for %s"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:337
#, python-format
msgid "Changes for %s"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:347
msgid "Informational notes"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:235
msgid "apt-listchanges: News"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:237
msgid "apt-listchanges: Changelogs"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:246
#, python-format
msgid "apt-listchanges: news for %s"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:249
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr ""

#: ../apt-listchanges.py:175
msgid "Didn't find any valid .deb archives"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:366
#, python-format
msgid "%s: will be newly installed"
msgstr ""

#: ../apt-listchanges.py:221
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr ""

#: ../apt-listchanges.py:225
#, python-format
msgid "%(pkg)s: Version %(version)s is lower than version of related packages (%(maxversion)s)"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:415
msgid "Binary NMU of"
msgstr ""

#: ../apt_listchanges/apt_listchanges.py:275
#, python-format
msgid "Received signal %d, exiting"
msgstr ""

#: ../apt_listchanges/ALCApt.py:57
msgid "APT pipeline messages:"
msgstr ""

#: ../apt_listchanges/ALCApt.py:64
msgid "Packages list:"
msgstr ""

#: ../apt_listchanges/ALCApt.py:74
msgid "APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""

#: ../apt_listchanges/ALCApt.py:82
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr ""

#: ../apt_listchanges/ALCApt.py:85
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""

#: ../apt-listchanges/ALCApt.py:82
msgid "Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly updated."
msgstr ""

#: ../apt_listchanges/ALCApt.py:90
msgid "APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater than 2)."
msgstr ""

#: ../apt_listchanges/ALCApt.py:98
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr ""

#: ../apt_listchanges/ALCApt.py:105
msgid "Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:164
#, python-format
msgid "Unknown configuration file option: %s"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:179
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:186
#, python-format
msgid "Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""

#: ../apt_listchanges/ALCConfig.py:200
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:204
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:208
#, python-format
msgid "%(deb)s is not readable"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:315
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:325
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr ""

#: ../apt_listchanges/ALCConfig.py:333
msgid "--latest=<N> and --show-all are mutually exclusive"
msgstr ""

#: ../apt_listchanges/ALCLog.py:37 ../apt_listchanges/ALCLog.py:46
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr ""

#: ../apt_listchanges/ALCLog.py:41
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:54
msgid "Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:65
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr ""

#: ../apt_listchanges/ALCSeenDb.py:154
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr ""

#: ../apt_listchanges/AptListChangesGtk.py:51
msgid "apt-listchanges: Reading changelogs"
msgstr ""

#: ../apt_listchanges/AptListChangesGtk.py:53
msgid "Reading changelogs. Please wait."
msgstr ""

#: ../apt_listchanges/AptListChangesGtk.py:112
msgid "Continue Installation?"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid "Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt_listchanges/frontends.py:56
msgid "Aborting"
msgstr ""

#: ../apt_listchanges/frontends.py:61
#, python-format
msgid "Confirmation failed: %s"
msgstr ""

#: ../apt_listchanges/frontends.py:66
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr ""

#: ../apt_listchanges/frontends.py:87
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr ""

#: ../apt_listchanges/frontends.py:97
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr ""

#: ../apt_listchanges/frontends.py:104
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr ""

#: ../apt_listchanges/frontends.py:118
msgid "Available apt-listchanges frontends:"
msgstr ""

#: ../apt_listchanges/frontends.py:121
msgid "Choose a frontend by entering its number: "
msgstr ""

#: ../apt_listchanges/frontends.py:130 ../apt_listchanges/frontends.py:524
#, python-format
msgid "Error: %s"
msgstr ""

#: ../apt_listchanges/frontends.py:132
#, python-format
msgid "Using default frontend: %s"
msgstr ""

#: ../apt_listchanges/frontends.py:190
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr ""

#: ../apt_listchanges/frontends.py:212
#, python-format
msgid "The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""

#: ../apt_listchanges/frontends.py:325
msgid "Do you want to continue? [Y/n] "
msgstr ""

#: ../apt_listchanges/frontends.py:341 ../apt_listchanges/frontends.py:484
#: ../apt_listchanges/frontends.py:493
msgid "Reading changelogs"
msgstr ""

#: ../apt_listchanges/frontends.py:412 ../apt_listchanges/frontends.py:468
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr ""

#: ../apt_listchanges/frontends.py:494
msgid "Done"
msgstr ""

#: ../apt_listchanges/frontends.py:505
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr ""

#: ../apt_listchanges/frontends.py:554
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr ""

#: ../apt_listchanges/frontends.py:561
msgid "Cannot find suitable user to drop root privileges"
msgstr ""

#: ../apt_listchanges/frontends.py:589
#, python-format
msgid "None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:558
msgid "press q to quit"
msgstr ""

#: ../apt_listchanges/DebianFiles.py:121 ../apt_listchanges/DebianFiles.py:131
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr ""

#: ../apt_listchanges/DebianFiles.py:472
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr ""

#: ../apt_listchanges/DebianFiles.py:615
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr ""

#: ../apt_listchanges/DebianFiles.py:623
#, python-format
msgid "Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed with: %(errmsg)s"
msgstr ""

#: ../apt_listchanges/DebianFiles.py:632
#, python-format
msgid "Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get changelog': %(errmsg)s"
msgstr ""

#: ../apt_listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr ""

#: ../apt_listchanges/apt-listchanges.ui:43
msgid "The following changes are found in the packages you are about to install:"
msgstr ""

