# Alyaksandr Koshal <alyaksandr.koshal@gmail.com>, 2021
# Вася Пупкін, 2021
# Black Beard (blackbeardboy), 2021
# p k (pkuhto), 2021
# Heorhi Puhachou <h.puhachou@gmail.com>, 2021
# Aleh Gardzey, 2021.
msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-05-12 23:30+0000\n"
"PO-Revision-Date: 2024-03-04 17:28\n"
"Last-Translator: Ubuntu Belarusian Translators Team <Unknown>\n"
"Language-Team: Belarusian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2023-05-27 08:08+0000\n"
"X-Generator: Launchpad (build 060234aa1273238f7880ac19de947f3512a7e11c)\n"
"Language: be\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || n%10>=5 && n%10<=9 || n%100>=11 && n%100<=14 ? 2 : 3);\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: be\n"
"X-Crowdin-File: /main/noble/en_GB/po_apport-be.po\n"
"X-Crowdin-File-ID: 41\n"

#: ../kde/apport-kde.py:187 ../bin/apport-cli.py:195
#: ../debian/tmp/usr/share/apport/apport-kde.py:187
#: ../debian/tmp/usr/bin/apport-cli.py:195
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../gtk/apport-gtk.ui.h:6
#: ../gtk/apport-gtk.py:181 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Send problem report to the developers?"
msgstr ""

#: ../kde/apport-kde.py:195 ../debian/tmp/usr/share/apport/apport-kde.py:195
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../gtk/apport-gtk.ui.h:14
#: ../gtk/apport-gtk.py:188 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "Send"
msgstr ""

#: ../kde/apport-kde.py:201 ../kde/apport-kde.py:239
#: ../debian/tmp/usr/share/apport/apport-kde.py:201
#: ../debian/tmp/usr/share/apport/apport-kde.py:239
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../gtk/apport-gtk.py:169
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../kde/apport-kde.py:209 ../debian/tmp/usr/share/apport/apport-kde.py:209
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../gtk/apport-gtk.py:259
#, python-format
msgid "Package: %s"
msgstr ""

#: ../kde/apport-kde.py:215 ../debian/tmp/usr/share/apport/apport-kde.py:215
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../gtk/apport-gtk.py:265
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../kde/apport-kde.py:221 ../debian/tmp/usr/share/apport/apport-kde.py:221
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../gtk/apport-gtk.py:274
#: ../gtk/apport-gtk.py:289
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../kde/apport-kde.py:224 ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../gtk/apport-gtk.py:277
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../kde/apport-kde.py:232 ../kde/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-kde.py:232
#: ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../gtk/apport-gtk.py:216
msgid "Continue"
msgstr ""

#: ../kde/apport-kde.py:235 ../debian/tmp/usr/share/apport/apport-kde.py:235
msgid "Leave Closed"
msgstr ""

#: ../kde/apport-kde.py:236 ../kde/apport-kde.py:382
#: ../debian/tmp/usr/share/apport/apport-kde.py:236
#: ../debian/tmp/usr/share/apport/apport-kde.py:382
msgid "Relaunch"
msgstr ""

#: ../kde/apport-kde.py:242 ../debian/tmp/usr/share/apport/apport-kde.py:242
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:297 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../kde/apport-kde.py:246 ../debian/tmp/usr/share/apport/apport-kde.py:246
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../gtk/apport-gtk.py:299
msgid "Ignore future problems of this type"
msgstr ""

#: ../kde/apport-kde.py:290 ../debian/tmp/usr/share/apport/apport-kde.py:290
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../gtk/apport-gtk.py:573
msgid "Hide Details"
msgstr ""

#: ../kde/apport-kde.py:293 ../debian/tmp/usr/share/apport/apport-kde.py:293
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:569 ../gtk/apport-gtk.ui.h:11
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:569
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "Show Details"
msgstr ""

#: ../kde/apport-kde.py:316 ../debian/tmp/usr/share/apport/apport-kde.py:316
msgid "Username:"
msgstr "Імя карыстальніка:"

#: ../kde/apport-kde.py:317 ../debian/tmp/usr/share/apport/apport-kde.py:317
msgid "Password:"
msgstr "Пароль:"

#: ../kde/apport-kde.py:364 ../bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-kde.py:364
#: ../debian/tmp/usr/bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146 ../gtk/apport-gtk.py:146
msgid "(binary data)"
msgstr ""

#: ../kde/apport-kde.py:407 ../debian/tmp/usr/share/apport/apport-kde.py:407
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:408 ../bin/apport-cli.py:255
#: ../debian/tmp/usr/share/apport/apport-kde.py:408
#: ../debian/tmp/usr/bin/apport-cli.py:255
msgid "Collecting problem information"
msgstr ""

#: ../kde/apport-kde.py:409 ../debian/tmp/usr/share/apport/apport-kde.py:409
msgid "The collected information can be sent to the developers to improve the application. This might take a few minutes."
msgstr "Сабраную інфармацыю можна адправіць распрацоўшчыкам, каб палепшыць праграму. Гэта можа заняць некалькі хвілін."

#: ../kde/apport-kde.py:435 ../debian/tmp/usr/share/apport/apport-kde.py:435
msgid "Uploading Problem Information"
msgstr ""

#: ../kde/apport-kde.py:436 ../bin/apport-cli.py:268
#: ../debian/tmp/usr/share/apport/apport-kde.py:436
#: ../debian/tmp/usr/bin/apport-cli.py:268 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
msgid "Uploading problem information"
msgstr ""

#: ../kde/apport-kde.py:437 ../debian/tmp/usr/share/apport/apport-kde.py:437
#: ../gtk/apport-gtk.ui.h:19 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
msgid "The collected information is being sent to the bug tracking system. This might take a few minutes."
msgstr ""

#: ../kde/apport-kde.py:470 ../kde/apport-kde.py:505 ../kde/apport-kde.py:525
#: ../debian/tmp/usr/share/apport/apport-kde.py:470
#: ../debian/tmp/usr/share/apport/apport-kde.py:505
#: ../debian/tmp/usr/share/apport/apport-kde.py:525 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr ""

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:87 ../debian/tmp/usr/bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:100 ../debian/tmp/usr/bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../bin/apport-cli.py:164 ../debian/tmp/usr/bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../bin/apport-cli.py:196 ../debian/tmp/usr/bin/apport-cli.py:196
msgid "After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../bin/apport-cli.py:199 ../debian/tmp/usr/bin/apport-cli.py:199
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:203 ../debian/tmp/usr/bin/apport-cli.py:203
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:207 ../debian/tmp/usr/bin/apport-cli.py:207
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:208 ../debian/tmp/usr/bin/apport-cli.py:208
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../bin/apport-cli.py:209 ../debian/tmp/usr/bin/apport-cli.py:209
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../bin/apport-cli.py:211 ../bin/apport-cli.py:288 ../bin/apport-cli.py:320
#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:211
#: ../debian/tmp/usr/bin/apport-cli.py:288
#: ../debian/tmp/usr/bin/apport-cli.py:320
#: ../debian/tmp/usr/bin/apport-cli.py:341
msgid "&Cancel"
msgstr ""

#: ../bin/apport-cli.py:239 ../debian/tmp/usr/bin/apport-cli.py:239
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:245 ../bin/apport-cli.py:250
#: ../debian/tmp/usr/bin/apport-cli.py:245
#: ../debian/tmp/usr/bin/apport-cli.py:250
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:249 ../debian/tmp/usr/bin/apport-cli.py:249
#, python-format
msgid "Error: %s"
msgstr ""

#: ../bin/apport-cli.py:256 ../debian/tmp/usr/bin/apport-cli.py:256
msgid "The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr "Сабраная інфармацыя можа быць накіравана распрацоўшчыкам для\n"
"паляпшэння праграмы. Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:269 ../debian/tmp/usr/bin/apport-cli.py:269
msgid "The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:319 ../debian/tmp/usr/bin/apport-cli.py:319
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:326 ../debian/tmp/usr/bin/apport-cli.py:326
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:342 ../debian/tmp/usr/bin/apport-cli.py:342
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:356 ../debian/tmp/usr/bin/apport-cli.py:356
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:362 ../debian/tmp/usr/bin/apport-cli.py:362
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:364 ../debian/tmp/usr/bin/apport-cli.py:364
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:370 ../debian/tmp/usr/bin/apport-cli.py:370
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:372 ../debian/tmp/usr/bin/apport-cli.py:372
msgid "You can launch a browser now, or copy this URL into a browser on another computer."
msgstr ""

#: ../bin/apport-cli.py:374 ../debian/tmp/usr/bin/apport-cli.py:374
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:389 ../debian/tmp/usr/bin/apport-cli.py:389
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Выкарыстанне: %s <report> <target directory>"

#: ../bin/apport-unpack.py:42 ../debian/tmp/usr/bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Папка прызначэння існуе і яна не пустая."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid "This occurred during a previous suspend, and prevented the system from resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid "This occurred during a previous hibernation, and prevented the system from resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid "The resume processing hung very near the end and will have appeared to have completed normally."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:236
#: ../apport/ui.py:236
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:241
#: ../apport/ui.py:241
#, python-format
msgid "This does not seem to be an official %s package. Please retry after updating the indexes of available packages, if that does not work then remove related third party packages and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:263
#: ../apport/ui.py:263
#, python-format
msgid "You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs:\n\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:400
#: ../apport/ui.py:400
msgid "unknown program"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:401
#: ../apport/ui.py:401
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:403
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1541
#: ../apport/ui.py:403 ../apport/ui.py:1541
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:404
#: ../apport/ui.py:404
msgid "Your computer does not have enough free memory to automatically analyze the problem and send a report to the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:459
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:467
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:616
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:619
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:824
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1374
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1513
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1517
#: ../apport/ui.py:459 ../apport/ui.py:467 ../apport/ui.py:616
#: ../apport/ui.py:619 ../apport/ui.py:824 ../apport/ui.py:1374
#: ../apport/ui.py:1513 ../apport/ui.py:1517
msgid "Invalid problem report"
msgstr "Няправільная справаздача пра памылку"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:460
#: ../apport/ui.py:460
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:463
#: ../apport/ui.py:463
msgid "Error"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:464
#: ../apport/ui.py:464
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:500
#: ../apport/ui.py:500
msgid "No PID specified"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:508
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:597
#: ../apport/ui.py:508 ../apport/ui.py:597
msgid "Invalid PID"
msgstr "Памылковы PID"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:509
#: ../apport/ui.py:509
msgid "The specified process ID does not exist."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:512
#: ../apport/ui.py:512
msgid "Not your PID"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:513
#: ../apport/ui.py:513
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:564
#: ../apport/ui.py:564
msgid "No package specified"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:565
#: ../apport/ui.py:565
msgid "You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:594
#: ../apport/ui.py:594
msgid "Permission denied"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:595
#: ../apport/ui.py:595
msgid "The specified process does not belong to you. Please run this program as the process owner or as root."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:598
#: ../apport/ui.py:598
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:617
#: ../apport/ui.py:617
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:620
#: ../apport/ui.py:620
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:649
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:828
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:849
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:854
#: ../apport/ui.py:649 ../apport/ui.py:828 ../apport/ui.py:849
#: ../apport/ui.py:854
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:664
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:710
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:726
#: ../apport/ui.py:664 ../apport/ui.py:710 ../apport/ui.py:726
msgid "Updating problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:665
#: ../apport/ui.py:665
msgid "You are not the reporter or subscriber of this problem report, or the report is a duplicate or already closed.\n\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:674
#: ../apport/ui.py:674
msgid "You are not the reporter of this problem report. It is much easier to mark a bug as a duplicate of another than to move your comments and attachments to a new bug.\n\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug\" and make a comment in this bug about the one you file.\n\n"
"Do you really want to proceed?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:711
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:727
#: ../apport/ui.py:711 ../apport/ui.py:727
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:778
#: ../apport/ui.py:778
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:795
#: ../apport/ui.py:795
msgid "Unknown symptom"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:796
#: ../apport/ui.py:796
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:829
#: ../apport/ui.py:829
msgid "The window option cannot be used on Wayland.\n\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n\n"
"The process ID can be found by running the System Monitor application. In the Processes tab, scroll until you find the correct application. The process ID is the number listed in the ID column."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:840
#: ../apport/ui.py:840
msgid "After closing this message please click on an application window to report a problem about it."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:850
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:855
#: ../apport/ui.py:850 ../apport/ui.py:855
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:869
#: ../apport/ui.py:869
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:871
#: ../apport/ui.py:871
msgid "Specify package name."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:873
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:925
#: ../apport/ui.py:873 ../apport/ui.py:925
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:904
#: ../apport/ui.py:904
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:907
#: ../apport/ui.py:907
msgid "Start in bug filing mode. Requires --package and an optional --pid, or just a --pid. If neither is given, display a list of known symptoms. (Implied if a single argument is given.)"
msgstr "Запуск у рэжыме адпраўкі справаздачы аб памылцы. Патрабуе параметр --package і неабавязковы --pid або толькі --pid. Калі параметры не перададзеныя, паказвае спіс вядомых сімптомаў. (Ужываецца, калі перададзены адзіны аргумент.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:909
#: ../apport/ui.py:909
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:911
#: ../apport/ui.py:911
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:913
#: ../apport/ui.py:913
msgid "File a bug report about a symptom. (Implied if symptom name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:915
#: ../apport/ui.py:915
msgid "Specify package name in --file-bug mode. This is optional if a --pid is specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:917
#: ../apport/ui.py:917
msgid "Specify a running program in --file-bug mode. If this is specified, the bug report will contain more information.  (Implied if pid is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:919
#: ../apport/ui.py:919
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:921
#: ../apport/ui.py:921
#, python-format
msgid "Report the crash from given .apport or .crash file instead of the pending ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:923
#: ../apport/ui.py:923
msgid "In bug filing mode, save the collected information into a file instead of reporting it. This file can then be reported later on from a different machine."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:927
#: ../apport/ui.py:927
msgid "Print the Apport version number."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1078
#: ../apport/ui.py:1078
msgid "This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1079
#: ../apport/ui.py:1079
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1080
#: ../apport/ui.py:1080
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1082
#: ../apport/ui.py:1082
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1118
#: ../apport/ui.py:1118
msgid "Can't remember send report status settings"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1119
#: ../apport/ui.py:1119
msgid "Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1178
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1188
#: ../apport/ui.py:1178 ../apport/ui.py:1188
msgid "This problem report applies to a program which is not installed any more."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1203
#: ../apport/ui.py:1203
#, python-format
msgid "The problem happened with the program %s which changed since the crash occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1250
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1331
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1519
#: ../apport/ui.py:1250 ../apport/ui.py:1331 ../apport/ui.py:1519
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1255
#: ../apport/ui.py:1255
msgid "This report is about a package that is not installed."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1259
#: ../apport/ui.py:1259
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1269
#: ../apport/ui.py:1269
msgid "You have two versions of this application installed, which one do you want to report a bug against?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1270
#: ../apport/ui.py:1270
#, python-format
msgid "%s snap"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1271
#: ../apport/ui.py:1271
#, python-format
msgid "%s deb package"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1304
#: ../apport/ui.py:1304
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1306
#: ../apport/ui.py:1306
#, python-format
msgid "%s is provided by a snap published by %s. No contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1375
#: ../apport/ui.py:1375
msgid "Could not determine the package or source package name."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1393
#: ../apport/ui.py:1393
msgid "Unable to start web browser"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1394
#: ../apport/ui.py:1394
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Немагчыма запусціць вэб-браўзер, каб адкрыць %s."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1467
#: ../apport/ui.py:1467
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1479
#: ../apport/ui.py:1479
msgid "Network problem"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1481
#: ../apport/ui.py:1481
msgid "Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1508
#: ../apport/ui.py:1508
msgid "Memory exhaustion"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1509
#: ../apport/ui.py:1509
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1544
#: ../apport/ui.py:1544
#, python-format
msgid "The problem cannot be reported:\n\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1600
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1607
#: ../apport/ui.py:1600 ../apport/ui.py:1607
msgid "Problem already known"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1601
#: ../apport/ui.py:1601
msgid "This problem was already reported in the bug report displayed in the web browser. Please check if you can add any further information that might be helpful for the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1608
#: ../apport/ui.py:1608
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid "Start an interactive gdb session with the report's core dump (-o ignored; does not rewrite report)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid "Write modified report to given file instead of changing the original report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid "Build a temporary sandbox and download/install the necessary packages and debug symbols in there; without this option it assumes that the necessary packages and debug symbols are already installed in the system. The argument points to the packaging system configuration base directory; if you specify \"system\", it will use the system configuration files, but will then only be able to retrace crashes that happened on the currently running release."
msgstr "Стварыць часовае асяроддзе, а пасля гэтага спампаваць/усталяваць у яе неабходныя пакеты і адладачныя сімвалы; без гэтага параметра мяркуецца, што неабходныя пакеты і адладачныя сімвалы ўжо ўсталяваны ў сістэме. Аргумент указвае на базавую папку канфігурацыі сістэмы пакетаў; калі вы пазначылі \"system\", то будуць выкарыстоўвацца сістэмныя файлы канфігурацыі, але толькі ў выпадку выяўлення аварыйных сітуацый, якія адбыліся ў выпуску сістэмы і якая працуе ў дадзены момант."

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Build another temporary sandbox for installing gdb and its dependencies using the same release as the report rather than whatever version of gdb you have installed."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid "Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Папка для захавання пакетаў, якія спампаваны ў часовае асяроддзе"

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid "Directory for unpacked packages. Future runs will assume that any already downloaded package is also extracted to this sandbox."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-retrace.py:65
msgid "Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid "Path to a file with the crash database authentication information. This is used when specifying a crash ID to upload the retraced stack traces (only if neither -g, -o, nor -s are specified)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid "Display retraced stack traces and ask for confirmation before sending them to the crash database."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:71 ../bin/apport-retrace.py:71
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:73 ../bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:82 ../bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:115 ../bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Адправіць іх як далучэнні? [так/не]"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid "reuse a previously created sandbox dir (SDIR) or, if it does not exist, create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid "do  not  create  or reuse a sandbox directory for additional debug symbols but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid "reuse a previously created cache dir (CDIR) or, if it does not exist, create it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid "the executable that is run under valgrind's memcheck tool  for memory leak detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:200
#: ../data/general-hooks/ubuntu.py:200
msgid "An Ubuntu package has a file conflict with a package that is not a genuine Ubuntu package."
msgstr ""

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:208
#: ../data/general-hooks/ubuntu.py:208
msgid "You have already encountered this package installation failure."
msgstr ""

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:224
#: ../data/general-hooks/ubuntu.py:224
msgid "Your system was initially configured with grub version 2, but you have removed it from your system in favor of grub 1 without configuring it.  To ensure your bootloader configuration is updated whenever a new kernel is available, open a terminal and run:\n\n"
"      sudo apt-get install grub-pc\n"
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../data/kernel_oops.py:29 ../debian/tmp/usr/share/apport/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасаваць"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid "Information is being collected that may help the developers fix the problem you report."
msgstr ""

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../kde/apport-kde-mime.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../kde/apport-kde-mime.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid "Authentication is required to collect system information for this problem report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""

