# Ukrainian translation for swift
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the swift package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: swift\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2011-01-26 23:59+0000\n"
"PO-Revision-Date: 2018-02-23 23:18+0000\n"
"Last-Translator: Andrii Prokopenko <Unknown>\n"
"Language-Team: Ukrainian <uk@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-04-15 10:10+0000\n"
"X-Generator: Launchpad (build 67d34a19aaa1df7be4dd8bf498cbc5bbd785067b)\n"

#: swift/account/auditor.py:52 swift/account/auditor.py:75
#, python-format
msgid ""
"Since %(time)s: Account audits: %(passed)s passed audit, %(failed)s failed "
"audit"
msgstr ""
"З %(time)s: Аудит облікового запису: %(passed)s аудит пройдено, %(failed)s "
"помилка аудиту"

#: swift/account/auditor.py:100 swift/container/auditor.py:103
#, python-format
msgid "Audit passed for %s"
msgstr "Аудит пройдено для %s"

#: swift/account/auditor.py:103
#, python-format
msgid "ERROR Could not get account info %s"
msgstr "ПОМИЛКА Не вдалося отримати реєстраційні дані %s"

#: swift/account/reaper.py:80 swift/container/updater.py:64
#, python-format
msgid "Loading account ring from %s"
msgstr "Завантаження кільця облікового запису з %s"

#: swift/account/reaper.py:88 swift/obj/updater.py:57
#, python-format
msgid "Loading container ring from %s"
msgstr "Завантаження кільця контейнера з %s"

#: swift/account/reaper.py:96
#, python-format
msgid "Loading object ring from %s"
msgstr "Завантаження кільця об'єкту з %s"

#: swift/account/reaper.py:106
msgid "Daemon started."
msgstr "Служба запущена."

#: swift/account/reaper.py:122
#, python-format
msgid "Begin devices pass: %s"
msgstr "Почати прохід пристроїв: %s"

#: swift/account/reaper.py:128 swift/common/utils.py:805
#: swift/obj/updater.py:74 swift/obj/updater.py:113
#, python-format
msgid "Skipping %s as it is not mounted"
msgstr "%s не примонтовано, пропускається"

#: swift/account/reaper.py:132
#, python-format
msgid "Devices pass completed: %.02fs"
msgstr "Прохід пристроїв виконаний: %.02fs"

#: swift/account/reaper.py:215
#, python-format
msgid "Beginning pass on account %s"
msgstr "Починається прохід для облікового запису %s"

#: swift/account/reaper.py:238
#, python-format
msgid "Exception with containers for account %s"
msgstr "Виключення з контейнерами для облікового запису %s"

#: swift/account/reaper.py:243
#, python-format
msgid "Exception with account %s"
msgstr "Виключення з обліковим записом %s"

#: swift/account/reaper.py:244
#, python-format
msgid "Incomplete pass on account %s"
msgstr "Не завершено прохід для облікового запису %s"

#: swift/account/reaper.py:246
#, python-format
msgid ", %s containers deleted"
msgstr ", %s контейнерів вилучено"

#: swift/account/reaper.py:248
#, python-format
msgid ", %s objects deleted"
msgstr ", %s об’єктів вилучено"

#: swift/account/reaper.py:250
#, python-format
msgid ", %s containers remaining"
msgstr ", %s контейнерів залишилося"

#: swift/account/reaper.py:253
#, python-format
msgid ", %s objects remaining"
msgstr ", %s об’єктів залишилося"

#: swift/account/reaper.py:255
#, python-format
msgid ", %s containers possibly remaining"
msgstr ", можливо залишилося %s контейнерів"

#: swift/account/reaper.py:258
#, python-format
msgid ", %s objects possibly remaining"
msgstr ", можливо залишилося %s об’єктів"

#: swift/account/reaper.py:261
msgid ", return codes: "
msgstr ", коди повернення: "

#: swift/account/reaper.py:265
#, python-format
msgid ", elapsed: %.02fs"
msgstr ", пройшло: %.02fs"

#: swift/account/reaper.py:320 swift/account/reaper.py:355
#: swift/account/reaper.py:406 swift/container/updater.py:277
#, python-format
msgid "Exception with %(ip)s:%(port)s/%(device)s"
msgstr "Виключення з %(ip)s:%(port)s/%(device)s"

#: swift/account/reaper.py:333
#, python-format
msgid ""
"Exception with objects for container %(container)s for account %(account)s"
msgstr ""
"Виключна ситуація в об’єктах для контейнера %(container)s для облікового "
"запису %(account)s"

#: swift/account/server.py:309 swift/container/server.py:397
#: swift/obj/server.py:597
#, python-format
msgid "ERROR __call__ error with %(method)s %(path)s "
msgstr "Помилка: помилка __call__ в %(method)s %(path)s "

#: swift/auth/server.py:96 swift/common/middleware/swauth.py:94
msgid "No super_admin_key set in conf file! Exiting."
msgstr "У конфігураційному файлі не вказано super_admin_key ! Вихід."

#: swift/auth/server.py:152
#, python-format
msgid ""
"\n"
"THERE ARE ACCOUNTS IN YOUR auth.db THAT DO NOT BEGIN WITH YOUR NEW RESELLER\n"
"PREFIX OF \"%(reseller)s\".\n"
"YOU HAVE A FEW OPTIONS:\n"
"    1. RUN \"swift-auth-update-reseller-prefixes %(db_file)s "
"%(reseller)s\",\n"
"       \"swift-init auth-server restart\", AND\n"
"       \"swift-auth-recreate-accounts -K ...\" TO CREATE FRESH ACCOUNTS.\n"
"    OR\n"
"    2. REMOVE %(db_file)s, RUN \"swift-init auth-server restart\", AND RUN\n"
"       \"swift-auth-add-user ...\" TO CREATE BRAND NEW ACCOUNTS THAT WAY.\n"
"    OR\n"
"    3. ADD \"reseller_prefix = %(previous)s\" (WITHOUT THE QUOTES) TO YOUR\n"
"       proxy-server.conf IN THE [filter:auth] SECTION AND TO YOUR\n"
"       auth-server.conf IN THE [app:auth-server] SECTION AND RUN\n"
"       \"swift-init proxy-server restart\" AND \"swift-init auth-server "
"restart\"\n"
"       TO REVERT BACK TO YOUR PREVIOUS RESELLER PREFIX.\n"
"\n"
"    %(note)s\n"
"                    "
msgstr ""
"\n"
"В ФАЙЛІ auth.db ЗНАХОДЯТЬСЯ ОБЛІКОВІ ЗАПИСИ ЩО НЕ ПОЧИНАЮТЬСЯ З ПРЕФІКСУ\n"
"НОВОГО ПРОДАВЦЯ «%(reseller)s».\n"
"У ВАС Є КІЛЬКА ВАРІАНТІВ:\n"
"    1. ВИКОНАТИ «swift-auth-update-reseller-prefixes %(db_file)s "
"%(reseller)s»,\n"
"       «swift-init auth-server restart», ТА\n"
"       «swift-auth-recreate-accounts -K ...» ЩОБ СТВОРИТИ НОВІ ОБЛІКОВІ "
"ЗАПИСИ.\n"
"    ЧИ\n"
"    2. ВИЛУЧИТИ %(db_file)s, ВИКОНАТИ «swift-init auth-server restart», ТА "
"ВИКОНАТИ\n"
"       «swift-auth-add-user ...» НОВІ ОБЛІКОВІ ЗАПИСИ В ТАКИЙ СПОСІБ.\n"
"    ЧИ\n"
"    3. ДОДАТИ «reseller_prefix = %(previous)s» (БЕЗ ЛАПОК) ДО\n"
"       proxy-server.conf У РОЗДІЛ [filter:auth] ТА\n"
"       auth-server.conf У РОЗДІЛ [app:auth-server] ТА ВИКОНАТИ\n"
"       «swift-init proxy-server restart» ТА «swift-init auth-server "
"restart»\n"
"       ЩОБ ПОВЕРНУТИСЯ ДО ПРЕФІКСА ПОПЕРЕДНЬОГО ПРОДАВЦЯ.\n"
"\n"
"    %(note)s\n"
"                    "

#: swift/auth/server.py:173
msgid ""
"\n"
"    SINCE YOUR PREVIOUS RESELLER PREFIX WAS AN EMPTY STRING, IT IS NOT\n"
"    RECOMMENDED TO PERFORM OPTION 3 AS THAT WOULD MAKE SUPPORTING MULTIPLE\n"
"    RESELLERS MORE DIFFICULT.\n"
"                    "
msgstr ""
"\n"
"    ОСКІЛЬКИ ПРЕФІКС ПОПЕРЕДНЬОГО ПРОДАВЦЯ БУВ ПОРОЖНІМ\n"
"    НЕ РЕКОМЕНДУЄТЬСЯ ВИКОНУВАТИ ВАРІАНТ 3 ОСКІЛЬКИ ЦЕ УСКЛАДНИТЬ\n"
"    ПІДТРИМКУ КІЛЬКОХ ПРОДАВЦІВ.\n"
"                    "

#: swift/auth/server.py:178
msgid "CRITICAL: "
msgstr "КРИТИЧНО: "

#: swift/auth/server.py:213
#, python-format
msgid "ERROR attempting to create account %(url)s: %(status)s %(reason)s"
msgstr ""
"ПОМИЛКА при спробі створення облікового запису %(url)s: %(status)s %(reason)s"

#: swift/auth/server.py:346
#, python-format
msgid ""
"ALREADY EXISTS create_user(%(account)s, %(user)s, _, %(admin)s, "
"%(reseller_admin)s) [%(elapsed).02f]"
msgstr ""
"ВЖЕ ІСНУЄ create_user(%(account)s, %(user)s, _, %(admin)s, "
"%(reseller_admin)s) [%(elapsed).02f]"

#: swift/auth/server.py:364
#, python-format
msgid ""
"FAILED create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"[%(elapsed).02f]"
msgstr ""
"ЗБІЙ create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"[%(elapsed).02f]"

#: swift/auth/server.py:381
#, python-format
msgid ""
"SUCCESS create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"= %(url)s [%(elapsed).02f]"
msgstr ""
"УСПІШНО create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"= %(url)s [%(elapsed).02f]"

#: swift/auth/server.py:656
msgid "ERROR Unhandled exception in ReST request"
msgstr "ПОМИЛКА Необроблюване виключення у запиті ReST"

#: swift/common/bench.py:85
#, python-format
msgid "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"
msgstr "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"

#: swift/common/bench.py:97
msgid "CannotSendRequest.  Skipping..."
msgstr "Неможливо послати запит. Пропускається..."

#: swift/common/bufferedhttp.py:96
#, python-format
msgid ""
"HTTP PERF: %(time).5f seconds to %(method)s %(host)s:%(port)s %(path)s)"
msgstr ""
"HTTP PERF: %(time).5f секунд до %(method)s %(host)s:%(port)s %(path)s)"

#: swift/common/db.py:299
msgid "Broker error trying to rollback locked connection"
msgstr "Помилка посередника при спробі відкату заблокованого з’єднання"

#: swift/common/db.py:754 swift/common/db.py:1221
#, python-format
msgid "Invalid pending entry %(file)s: %(entry)s"
msgstr "Неприпустимий очікуючий запис %(file)s: %(entry)s"

#: swift/common/db_replicator.py:84
#, python-format
msgid "ERROR reading HTTP response from %s"
msgstr "ПОМИЛКА читання HTTP-відповіді від %s"

#: swift/common/db_replicator.py:123
#, python-format
msgid ""
"Attempted to replicate %(count)d dbs in %(time).5f seconds (%(rate).5f/s)"
msgstr ""
"Спроба копіювання %(count)d БД через %(time).5f секунд (%(rate).5f/s)"

#: swift/common/db_replicator.py:129
#, python-format
msgid "Removed %(remove)d dbs"
msgstr "Вилучено %(remove)d dbs"

#: swift/common/db_replicator.py:130
#, python-format
msgid "%(success)s successes, %(failure)s failures"
msgstr "%(success)s успішно, %(failure)s помилково"

#: swift/common/db_replicator.py:155
#, python-format
msgid "ERROR rsync failed with %(code)s: %(args)s"
msgstr "ПОМИЛКА Збій rsync з %(code)s: %(args)s"

#: swift/common/db_replicator.py:205
#, python-format
msgid "Syncing chunks with %s"
msgstr "Синхронізація фрагментів даних з %s"

#: swift/common/db_replicator.py:213
#, python-format
msgid "ERROR Bad response %(status)s from %(host)s"
msgstr "Помилка: Неправильний запит %(status)s із %(host)s"

#: swift/common/db_replicator.py:278
#, python-format
msgid "ERROR Unable to connect to remote server: %s"
msgstr "ПОМИЛКА: Неможливо під’єднатися до віддаленого сервера: %s"

#: swift/common/db_replicator.py:316
#, python-format
msgid "Replicating db %s"
msgstr "Копіювання db %s"

#: swift/common/db_replicator.py:325 swift/common/db_replicator.py:479
#, python-format
msgid "Quarantining DB %s"
msgstr "Переміщення у карантин DB %s"

#: swift/common/db_replicator.py:328
#, python-format
msgid "ERROR reading db %s"
msgstr "ПОМИЛКА читання db %s"

#: swift/common/db_replicator.py:361
#, python-format
msgid "ERROR Remote drive not mounted %s"
msgstr "ПОМИЛКА: віддалений диск не примонтовано %s"

#: swift/common/db_replicator.py:363
#, python-format
msgid "ERROR syncing %(file)s with node %(node)s"
msgstr "ПОМИЛКА синхронізації %(file)s з вузлом %(node)s"

#: swift/common/db_replicator.py:405
msgid "ERROR Failed to get my own IPs?"
msgstr "ПОМИЛКА: Не вдалося отримати мої власні IP?"

#: swift/common/db_replicator.py:412
#, python-format
msgid "Skipping %(device)s as it is not mounted"
msgstr "Пропуск %(device)s - пристрій не примонтовано"

#: swift/common/db_replicator.py:420
msgid "Beginning replication run"
msgstr "Запуск копіювання"

#: swift/common/db_replicator.py:425
msgid "Replication run OVER"
msgstr "Копіювання ЗАВЕРШЕНО"

#: swift/common/db_replicator.py:436
msgid "ERROR trying to replicate"
msgstr "ПОМИЛКА копіювання"

#: swift/common/memcached.py:69
#, python-format
msgid "Timeout %(action)s to memcached: %(server)s"
msgstr "Тайм-аут дії %(action)s для збереження в кеш пам’яті: %(server)s"

#: swift/common/memcached.py:72
#, python-format
msgid "Error %(action)s to memcached: %(server)s"
msgstr "Помилка дії %(action)s для збереження в кеш пам’яті: %(server)s"

#: swift/common/memcached.py:81
#, python-format
msgid "Error limiting server %s"
msgstr "Помилка обмеження сервера %s"

#: swift/common/utils.py:88
#, python-format
msgid "Unable to locate %s in libc.  Leaving as a no-op."
msgstr "Не вдалося знайти %s в libc. Залишено як no-op."

#: swift/common/utils.py:255
msgid "STDOUT: Connection reset by peer"
msgstr "STDOUT: З’єднання скинуто сервером"

#: swift/common/utils.py:257 swift/common/utils.py:260
#, python-format
msgid "STDOUT: %s"
msgstr "STDOUT: %s"

#: swift/common/utils.py:324
msgid "Connection refused"
msgstr "У з'єднанні відмовлено"

#: swift/common/utils.py:326
msgid "Host unreachable"
msgstr "Хост недоступний"

#: swift/common/utils.py:328
msgid "Connection timeout"
msgstr "Припустимий час очікування для з’єднання вичерпано"

#: swift/common/utils.py:464
msgid "UNCAUGHT EXCEPTION"
msgstr "НЕОБРОБЛЮВАНА ВИНЯТКОВА СИТУАЦІЯ"

#: swift/common/utils.py:511
msgid "Error: missing config file argument"
msgstr "Помилка: відсутній аргумент конфігураційного файлу"

#: swift/common/utils.py:516
#, python-format
msgid "Error: unable to locate %s"
msgstr "Помилка: неможливо знайти %s"

#: swift/common/utils.py:743
#, python-format
msgid "Unable to read config file %s"
msgstr "Неможливо прочитати конфігураційний файл %s"

#: swift/common/utils.py:749
#, python-format
msgid "Unable to find %s config section in %s"
msgstr "Неможливо знайти %s розділ налаштування у %s"

#: swift/common/middleware/catch_errors.py:39
#, python-format
msgid "Error: %s"
msgstr "Помилка: %s"

#: swift/common/middleware/cname_lookup.py:91
#, python-format
msgid "Mapped %(given_domain)s to %(found_domain)s"
msgstr "Перетворено %(given_domain)s в %(found_domain)s"

#: swift/common/middleware/cname_lookup.py:102
#, python-format
msgid "Following CNAME chain for  %(given_domain)s to %(found_domain)s"
msgstr "Наступний ланцюжок CNAME для %(given_domain)s в %(found_domain)s"

#: swift/common/middleware/ratelimit.py:172
msgid "Returning 497 because of blacklisting"
msgstr "Повертаємо 497 через чорний список"

#: swift/common/middleware/ratelimit.py:185
#, python-format
msgid ""
"Ratelimit sleep log: %(sleep)s for %(account)s/%(container)s/%(object)s"
msgstr ""
"Протокол тайм-ауту при обмеженні швидкості %(sleep)s для "
"%(account)s/%(container)s/%(object)s"

#: swift/common/middleware/ratelimit.py:192
#, python-format
msgid "Returning 498 because of ops rate limiting (Max Sleep) %s"
msgstr ""
"Повертає 498 через обмеження кількості операції (максимальний час сну) %s"

#: swift/common/middleware/ratelimit.py:212
msgid "Warning: Cannot ratelimit without a memcached client"
msgstr ""
"Попередження: не вдається обмежити швидкість без клієнта з кешуванням пам’яті"

#: swift/common/middleware/swauth.py:635
#, python-format
msgid ""
"ERROR: Exception while trying to communicate with "
"%(scheme)s://%(host)s:%(port)s/%(path)s"
msgstr ""
"ПОМИЛКА: Виняткова ситуація при спробі зв'язку з "
"%(scheme)s://%(host)s:%(port)s/%(path)s"

#: swift/container/auditor.py:54 swift/container/auditor.py:78
#, python-format
msgid ""
"Since %(time)s: Container audits: %(pass)s passed audit, %(fail)s failed "
"audit"
msgstr ""
"Виконано перевірок контейнера: %(time)s, з них успішно: %(pass)s, з "
"помилками: %(fail)s"

#: swift/container/auditor.py:68
msgid "Begin container audit \"once\" mode"
msgstr "Почати перевірку контейнера в \"однократному\" режимі"

#: swift/container/auditor.py:88
#, python-format
msgid "Container audit \"once\" mode completed: %.02fs"
msgstr "Перевірка контейнера в \"однократному\" режимі завершена: %.02fs"

#: swift/container/auditor.py:106
#, python-format
msgid "ERROR Could not get container info %s"
msgstr "Помилка Неможливо отримати інформацію про контейнер %s"

#: swift/container/server.py:114
#, python-format
msgid ""
"ERROR Account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): Response %(status)s %(reason)s"
msgstr ""
"ПОМИЛКА Збій оновлення облікового запису з %(ip)s:%(port)s/%(device)s "
"(спроба буде повторена пізніше): Відповідь %(status)s %(reason)s"

#: swift/container/server.py:122
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later)"
msgstr ""
"ПОМИЛКА оновлення облікового запису з %(ip)s:%(port)s/%(device)s (спроба "
"буде повторена пізніше)"

#: swift/container/updater.py:78 swift/obj/replicator.py:492
#, python-format
msgid "%s is not mounted"
msgstr "%s не змонтовано"

#: swift/container/updater.py:97
#, python-format
msgid "ERROR with loading suppressions from %s: "
msgstr "Помилка при завантаженні прихованих об’єктів із %s: "

#: swift/container/updater.py:107
msgid "Begin container update sweep"
msgstr "Почати суцільну перевірку оновлень контейнера"

#: swift/container/updater.py:140
#, python-format
msgid ""
"Container update sweep of %(path)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"Суцільна перевірка оновлень контейнера в %(path)s завершена: "
"%(elapsed).02fs, успішно: %(success)s, збоїв: %(fail)s, без змін: "
"%(no_change)s"

#: swift/container/updater.py:154
#, python-format
msgid "Container update sweep completed: %.02fs"
msgstr "Суцільна перевірка оновлень контейнера завершена: %.02fs"

#: swift/container/updater.py:164
msgid "Begin container update single threaded sweep"
msgstr "Почати однониткову суцільну перевірку оновлень контейнера"

#: swift/container/updater.py:172
#, python-format
msgid ""
"Container update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"Суцільна однониткова перевірка оновлень контейнера завершена: "
"%(elapsed).02fs, успішно: %(success)s, збоїв: %(fail)s, без змін: "
"%(no_change)s"

#: swift/container/updater.py:224
#, python-format
msgid "Update report sent for %(container)s %(dbfile)s"
msgstr "Звіт оновлення надіслано для %(container)s %(dbfile)s"

#: swift/container/updater.py:232
#, python-format
msgid "Update report failed for %(container)s %(dbfile)s"
msgstr "Збій звіту про оновлення для %(container)s %(dbfile)s"

#: swift/container/updater.py:266
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): "
msgstr ""
"Помилка: оновлення облікового запису не виконано для "
"%(ip)s:%(port)s/%(device)s (операція буде повторена пізніше): "

#: swift/obj/auditor.py:61
#, python-format
msgid "Begin object audit \"%s\" mode"
msgstr "Початок аудиту об'єкту в режимі «%s»"

#: swift/obj/auditor.py:73
#, python-format
msgid ""
"Since %(start_time)s: Locally: %(passes)d passed audit, %(quars)d "
"quarantined, %(errors)d errors files/sec: %(frate).2f , bytes/sec: "
"%(brate).2f"
msgstr ""
"За %(start_time)s: Локально: %(passes)d пройшли аудит, %(quars)d в "
"карантині, %(errors)d помилок файл/с: %(frate).2f , байт/с: %(brate).2f"

#: swift/obj/auditor.py:90
#, python-format
msgid ""
"Object audit \"%(mode)s\" mode completed: %(elapsed).02fs. Total files/sec: "
"%(frate).2f , Total bytes/sec: %(brate).2f "
msgstr ""
"Аудит об'єкту в режимі «%(mode)s» завершено: %(elapsed).02fs. Загалом "
"файл/сек: %(frate).2f , Загалом байт/сек: %(brate).2f "

#: swift/obj/auditor.py:141
#, python-format
msgid "ERROR Object %(obj)s failed audit and will be quarantined: %(err)s"
msgstr ""
"ПОМИЛКА Збій аудиту об’єкту %(obj)s, об’єкт буде поміщено у карантин: %(err)s"

#: swift/obj/auditor.py:150
#, python-format
msgid "ERROR Trying to audit %s"
msgstr "ПОМИЛКА Спроба аудиту %s"

#: swift/obj/replicator.py:182
msgid "Error hashing suffix"
msgstr "Помилка хешування суфіксу"

#: swift/obj/replicator.py:246
#, python-format
msgid "Killing long-running rsync: %s"
msgstr "Примусове завершення довго виконуваного rsync: %s"

#: swift/obj/replicator.py:257
#, python-format
msgid "Bad rsync return code: %(args)s -> %(ret)d"
msgstr "Зіпсований код повернення rsync: %(args)s -> %(ret)d"

#: swift/obj/replicator.py:261 swift/obj/replicator.py:265
#, python-format
msgid "Successful rsync of %(src)s at %(dst)s (%(time).03f)"
msgstr "Успішне виконання rsync для %(src)s на %(dst)s (%(time).03f)"

#: swift/obj/replicator.py:350
#, python-format
msgid "Removing partition: %s"
msgstr "Вилучення розділу: %s"

#: swift/obj/replicator.py:353
msgid "Error syncing handoff partition"
msgstr "Помилка при синхронізації розділу передачі керування"

#: swift/obj/replicator.py:383
#, python-format
msgid "%(ip)s/%(device)s responded as unmounted"
msgstr "%(ip)s/%(device)s відсутнє під’єднання"

#: swift/obj/replicator.py:388
#, python-format
msgid "Invalid response %(resp)s from %(ip)s"
msgstr "Неприпустима відповідь %(resp)s від %(ip)s"

#: swift/obj/replicator.py:410
#, python-format
msgid "Error syncing with node: %s"
msgstr "Помилка синхронізації з вузлом: %s"

#: swift/obj/replicator.py:414
msgid "Error syncing partition"
msgstr "Помилка синхронізації розділу"

#: swift/obj/replicator.py:424
#, python-format
msgid ""
"%(replicated)d/%(total)d (%(percentage).2f%%) partitions replicated in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""
"%(replicated)d/%(total)d (%(percentage).2f%%) розділів скопійовано за "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"

#: swift/obj/replicator.py:433
#, python-format
msgid ""
"%(checked)d suffixes checked - %(hashed).2f%% hashed, %(synced).2f%% synced"
msgstr ""
"Перевірено суфіксів: %(checked)d - хешовано: %(hashed).2f%%, синхронізовано: "
"%(synced).2f%%"

#: swift/obj/replicator.py:439
#, python-format
msgid "Partition times: max %(max).4fs, min %(min).4fs, med %(med).4fs"
msgstr ""
"Час розділу: максимум: %(max).4fs, мінімум: %(min).4fs, середній: %(med).4fs"

#: swift/obj/replicator.py:446
#, python-format
msgid "Nothing replicated for %s seconds."
msgstr "Нічого не репліковано за %s с."

#: swift/obj/replicator.py:475
msgid "Lockup detected.. killing live coros."
msgstr "Виявлено блокування.. примусове завершення працюючих модулів."

#: swift/obj/replicator.py:530
msgid "Ring change detected. Aborting current replication pass."
msgstr ""
"Виявлено кільцеву зміну. Примусове завершення поточного проходу реплікації."

#: swift/obj/replicator.py:540
msgid "Exception in top-level replication loop"
msgstr "Виключна ситуація у циклі реплікації верхнього рівню"

#: swift/obj/replicator.py:549
msgid "Running object replicator in script mode."
msgstr "Запуск засобу реплікації об’єктів у режимі сценаріїв."

#: swift/obj/replicator.py:553 swift/obj/replicator.py:565
#, python-format
msgid "Object replication complete. (%.02f minutes)"
msgstr "Копіювання об’єкту завершено. (%.02f minutes)"

#: swift/obj/replicator.py:560
msgid "Starting object replication pass."
msgstr "Запуск проходу реплікації об’єктів."

#: swift/obj/replicator.py:566
#, python-format
msgid "Replication sleeping for %s seconds."
msgstr "Копіювання у режимі очікування %s секунд."

#: swift/obj/server.py:313
#, python-format
msgid ""
"ERROR Container update failed (saving for async update later): %(status)d "
"response from %(ip)s:%(port)s/%(dev)s"
msgstr ""
"Помилка. Оновлення контейнера не виконано (збереження асинхронних оновлень "
"буде виконано пізніше): %(status)d відповідь від %(ip)s:%(port)s/%(dev)s"

#: swift/obj/server.py:319
#, python-format
msgid ""
"ERROR container update failed with %(ip)s:%(port)s/%(dev)s (saving for async "
"update later)"
msgstr ""
"Помилка. Оновлення контейнера не виконано з %(ip)s:%(port)s/%(dev)s "
"(збереження асинхронного оновлення буде виконано пізніше)"

#: swift/obj/updater.py:65
msgid "Begin object update sweep"
msgstr "Почати суцільну перевірку оновлень об’єкту"

#: swift/obj/updater.py:89
#, python-format
msgid ""
"Object update sweep of %(device)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr ""
"Суцільна перевірка оновлень об’єкту на пристрої %(device)s завершена: "
"%(elapsed).02fs, успішно: %(success)s, з помилками: %(fail)s"

#: swift/obj/updater.py:98
#, python-format
msgid "Object update sweep completed: %.02fs"
msgstr "Суцільна перевірка оновлень об’єкту завершена: %.02fs"

#: swift/obj/updater.py:105
msgid "Begin object update single threaded sweep"
msgstr "Почати однониткову суцільну перевірку оновлень об’єкту"

#: swift/obj/updater.py:117
#, python-format
msgid ""
"Object update single threaded sweep completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr ""
"Суцільна однониткова перевірка оновлень об’єкту завершена: %(elapsed).02fs, "
"%(success)s успішно, %(fail)s з помилками"

#: swift/obj/updater.py:157
#, python-format
msgid "ERROR Pickle problem, quarantining %s"
msgstr "Помилка Pickle, %s поміщається в карантин"

#: swift/obj/updater.py:177
#, python-format
msgid "Update sent for %(obj)s %(path)s"
msgstr "Оновлення для %(obj)s %(path)s"

#: swift/obj/updater.py:182
#, python-format
msgid "Update failed for %(obj)s %(path)s"
msgstr "Помилка оновлення %(obj)s %(path)s"

#: swift/obj/updater.py:206
#, python-format
msgid "ERROR with remote server %(ip)s:%(port)s/%(device)s"
msgstr "ПОМИЛКА віддаленого сервера %(ip)s:%(port)s/%(device)s"

#: swift/proxy/server.py:165 swift/proxy/server.py:629
#: swift/proxy/server.py:696 swift/proxy/server.py:712
#: swift/proxy/server.py:721 swift/proxy/server.py:1004
#: swift/proxy/server.py:1044 swift/proxy/server.py:1089
msgid "Object"
msgstr "Об’єкт"

#: swift/proxy/server.py:170
#, python-format
msgid "Could not load object segment %(path)s: %(status)s"
msgstr "Неможливо завантажити сегмент об’єкту %(path)s: %(status)s"

#: swift/proxy/server.py:177 swift/proxy/server.py:210
#: swift/proxy/server.py:257
#, python-format
msgid "ERROR: While processing manifest /%(acc)s/%(cont)s/%(obj)s"
msgstr "ПОМИЛКА: При обробці проявляється /%(acc)s/%(cont)s/%(obj)s"

#: swift/proxy/server.py:292
#, python-format
msgid "%(msg)s %(ip)s:%(port)s"
msgstr "%(msg)s %(ip)s:%(port)s"

#: swift/proxy/server.py:304
#, python-format
msgid "ERROR with %(type)s server %(ip)s:%(port)s/%(device)s re: %(info)s"
msgstr ""
"Помилка з сервером %(type)s %(ip)s:%(port)s/%(device)s, повернення: %(info)s"

#: swift/proxy/server.py:328
#, python-format
msgid "Node error limited %(ip)s:%(port)s (%(device)s)"
msgstr "Обмежена помилка вузла %(ip)s:%(port)s (%(device)s)"

#: swift/proxy/server.py:388 swift/proxy/server.py:1451
#: swift/proxy/server.py:1497 swift/proxy/server.py:1545
#: swift/proxy/server.py:1590
msgid "Account"
msgstr "Обліковий запис"

#: swift/proxy/server.py:389
#, python-format
msgid "Trying to get account info for %s"
msgstr "Спроба отримання даних про обліковий запис для %s"

#: swift/proxy/server.py:466 swift/proxy/server.py:740
#: swift/proxy/server.py:772 swift/proxy/server.py:1214
#: swift/proxy/server.py:1301 swift/proxy/server.py:1356
#: swift/proxy/server.py:1413
msgid "Container"
msgstr "Контейнер"

#: swift/proxy/server.py:467
#, python-format
msgid "Trying to get container info for %s"
msgstr "Спроба отримання даних про контейнер для %s"

#: swift/proxy/server.py:552
#, python-format
msgid "%(type)s returning 503 for %(statuses)s"
msgstr "%(type)s повернення 503 для %(statuses)s"

#: swift/proxy/server.py:598 swift/proxy/server.py:697
#, python-format
msgid "Trying to %(method)s %(path)s"
msgstr "Спроба %(method)s %(path)s"

#: swift/proxy/server.py:627
msgid "Client disconnected on read"
msgstr "Вимкнення клієнта при читанні"

#: swift/proxy/server.py:630
#, python-format
msgid "Trying to read during GET of %s"
msgstr "Спроба читання під час GET для %s"

#: swift/proxy/server.py:653
#, python-format
msgid "ERROR %(status)d %(body)s From %(type)s Server"
msgstr "ПОМИЛКА %(status)d %(body)s Від %(type)s сервера"

#: swift/proxy/server.py:692
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server"
msgstr "ПОМИЛКА %(status)d %(body)s Від Об’єкту Сервера"

#: swift/proxy/server.py:776 swift/proxy/server.py:783
#, python-format
msgid "Object manifest GET could not continue listing: %s %s"
msgstr "GET-маніфест об'єкту не може продовжити виведення списку: %s %s"

#: swift/proxy/server.py:905
msgid "Object POST"
msgstr "Об’єкт POST"

#: swift/proxy/server.py:1005
#, python-format
msgid "Expect: 100-continue on %s"
msgstr "Очікуване значення: 100-continue в %s"

#: swift/proxy/server.py:1017
#, python-format
msgid "Object PUT returning 503, %(conns)s/%(nodes)s required connections"
msgstr "PUT об'єкту повернув 503, %(conns)s/%(nodes)s необхідних з'єднань"

#: swift/proxy/server.py:1045
#, python-format
msgid "Trying to write to %s"
msgstr "Спроба зробитии запис у %s"

#: swift/proxy/server.py:1049
#, python-format
msgid ""
"Object PUT exceptions during send, %(conns)s/%(nodes)s required connections"
msgstr ""
"PUT об'єкту - виняткова ситуація під час відправки, %(conns)s/%(nodes)s "
"необхідних з'єднань"

#: swift/proxy/server.py:1058
#, python-format
msgid "ERROR Client read timeout (%ss)"
msgstr "Помилка: тайм-аут читання клієнта (%ss)"

#: swift/proxy/server.py:1063
msgid "ERROR Exception causing client disconnect"
msgstr "ПОМИЛКА Виключення, викликаюче від’єднання клієнта"

#: swift/proxy/server.py:1068
msgid "Client disconnected without sending enough data"
msgstr "Клієнт відімкнений без відправки даних"

#: swift/proxy/server.py:1083
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server re: %(path)s"
msgstr "Помилка %(status)d %(body)s, відповідь від сервера об’єкту: %(path)s"

#: swift/proxy/server.py:1090
#, python-format
msgid "Trying to get final status of PUT to %s"
msgstr "Спроба отримання кінцевого стану PUT в %s"

#: swift/proxy/server.py:1093
#, python-format
msgid "Object servers returned %s mismatched etags"
msgstr "Сервери об’єктів повернули невідповідні etag: %s"

#: swift/proxy/server.py:1101
msgid "Object PUT"
msgstr "Об’єкт PUT"

#: swift/proxy/server.py:1153
msgid "Object DELETE"
msgstr "Об’єкт DELETE"

#: swift/proxy/server.py:1302 swift/proxy/server.py:1498
#, python-format
msgid "Trying to PUT to %s"
msgstr "Спроба виконати PUT до %s"

#: swift/proxy/server.py:1314
msgid "Container PUT"
msgstr "Контейнер PUT"

#: swift/proxy/server.py:1357 swift/proxy/server.py:1546
#, python-format
msgid "Trying to POST %s"
msgstr "Спроба POST %s"

#: swift/proxy/server.py:1369
msgid "Container POST"
msgstr "Контейнер POST"

#: swift/proxy/server.py:1414 swift/proxy/server.py:1591
#, python-format
msgid "Trying to DELETE %s"
msgstr "Спроба DELETE %s"

#: swift/proxy/server.py:1426
msgid "Container DELETE"
msgstr "Контейнер DELETE"

#: swift/proxy/server.py:1433
msgid "Returning 503 because not all container nodes confirmed DELETE"
msgstr "Повернено 503, оскільки не усі вузли контейнера підтвердили DELETE"

#: swift/proxy/server.py:1508
msgid "Account PUT"
msgstr "PUT облікового запису"

#: swift/proxy/server.py:1556
msgid "Account POST"
msgstr "POST облікового запису"

#: swift/proxy/server.py:1601
msgid "Account DELETE"
msgstr "DELETE облікового запису"

#: swift/proxy/server.py:1757
msgid "ERROR Unhandled exception in request"
msgstr "ПОМИЛКА Необроблюване виключення у запиті"

#: swift/stats/access_processor.py:63 swift/stats/stats_processor.py:40
#, python-format
msgid "Bad line data: %s"
msgstr "Неприпустимі рядкові дані: %s"

#: swift/stats/access_processor.py:67
#, python-format
msgid "Bad server name: found \"%(found)s\" expected \"%(expected)s\""
msgstr ""
"Неприпустиме ім’я сервера: отримане \"%(found)s\" очікуване \"%(expected)s\""

#: swift/stats/access_processor.py:75
#, python-format
msgid "Invalid path: %(error)s from data: %(log)s"
msgstr "Неприпустимий шлях: %(error)s у даних: %(log)s"

#: swift/stats/access_processor.py:199
#, python-format
msgid ""
"I found a bunch of bad lines in %(name)s (%(bad)d bad, %(total)d total)"
msgstr ""
"Виявлено багато неприпустимих рядків у %(name)s (%(bad)d bad, %(total)d "
"total)"

#: swift/stats/account_stats.py:55
msgid "Gathering account stats"
msgstr "Збір статистики облікових записів"

#: swift/stats/account_stats.py:59
#, python-format
msgid "Gathering account stats complete (%0.2f minutes)"
msgstr "Збір статистики облікових записів завершено (%0.2f minutes)"

#: swift/stats/account_stats.py:75
#, python-format
msgid "Device %s is not mounted, skipping."
msgstr "Пристрій %s не змонтовано, пропуск."

#: swift/stats/account_stats.py:81
#, python-format
msgid "Path %s does not exist, skipping."
msgstr "Адреси %s не існує, пропуск."

#: swift/stats/log_processor.py:62
#, python-format
msgid "Loaded plugin \"%s\""
msgstr "Завантажена втулка \"%s\""

#: swift/stats/log_processor.py:79
#, python-format
msgid "Processing %(obj)s with plugin \"%(plugin)s\""
msgstr "Обробка %(obj)s з втулкою \"%(plugin)s\""

#: swift/stats/log_processor.py:179
#, python-format
msgid "Bad compressed data for %s"
msgstr "Пошкоджені стиснуті дані %s"

#: swift/stats/log_processor.py:240
msgid "Beginning log processing"
msgstr "Початок обробки журналу подій"

#: swift/stats/log_processor.py:278
#, python-format
msgid "found %d processed files"
msgstr "виявлено %d оброблених файлів"

#: swift/stats/log_processor.py:283
#, python-format
msgid "loaded %d files to process"
msgstr "завантажено %d файлів на обробку"

#: swift/stats/log_processor.py:286 swift/stats/log_processor.py:360
#, python-format
msgid "Log processing done (%0.2f minutes)"
msgstr "Обробка журналу подій завершена (%0.2f minutes)"

#: swift/stats/log_uploader.py:71
msgid "Uploading logs"
msgstr "Вивантаження звітів"

#: swift/stats/log_uploader.py:74
#, python-format
msgid "Uploading logs complete (%0.2f minutes)"
msgstr "Вивантаження звітів завершено (%0.2f минут)"

#: swift/stats/log_uploader.py:129
#, python-format
msgid "Unexpected log: %s"
msgstr "Неприпустимий журнал: %s"

#: swift/stats/log_uploader.py:135
#, python-format
msgid "Skipping log: %(file)s (< %(cutoff)d seconds old)"
msgstr "Пропуск журналу: %(file)s (< %(cutoff)d секунд тому)"

#: swift/stats/log_uploader.py:142
#, python-format
msgid "Log %s is 0 length, skipping"
msgstr "Log %s порожній, пропустити"

#: swift/stats/log_uploader.py:144
#, python-format
msgid "Processing log: %s"
msgstr "Опрацювання звіту: %s"

#: swift/stats/log_uploader.py:165
#, python-format
msgid "Uploaded log %(file)s to %(target)s"
msgstr "Завантажено журналів %(file)s в %(target)s"

#: swift/stats/log_uploader.py:170
#, python-format
msgid "ERROR: Upload of log %s failed!"
msgstr "ПОМИЛКА: Невдале завантаження журналу %s !"
