# Russian translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
# Igor Zubarev <igor4u@gmail.com>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2024-04-12 16:43+0000\n"
"PO-Revision-Date: 2024-04-13 20:26+0000\n"
"Last-Translator: Alexey Fedorov <Unknown>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2024-04-16 03:24+0000\n"
"X-Generator: Launchpad (build 67d34a19aaa1df7be4dd8bf498cbc5bbd785067b)\n"
"Language: ru\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:206 ../DistUpgrade/distro.py:474
#, python-format
msgid "Server for %s"
msgstr "Сервер для %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:225 ../DistUpgrade/distro.py:237
#: ../DistUpgrade/distro.py:258
msgid "Main server"
msgstr "Основной сервер"

#: ../DistUpgrade/distro.py:267
msgid "Custom servers"
msgstr "Пользовательские серверы"

#: ../DistUpgrade/DistUpgradeCache.py:182
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Удалить пакет с ошибками"
msgstr[1] "Удалить пакеты с ошибками"
msgstr[2] "Удалить пакеты с ошибками."

#: ../DistUpgrade/DistUpgradeCache.py:185
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Обновляемый пакет «%s» был установлен не до конца и должен быть "
"переустановлен, однако для него не найден соответствующий архив. Вы хотите "
"удалить этот пакет и продолжить?"
msgstr[1] ""
"Обновляемые пакеты «%s» были установлены не до конца и должны быть "
"переустановлены, однако, для них не найдены соответствующие архивы. Вы "
"хотите удалить эти пакеты и продолжить?"
msgstr[2] ""
"Обновляемые пакеты «%s» были установлены не до конца и должны быть "
"переустановлены, однако, для них не найдены соответствующие архивы. Вы "
"хотите удалить эти пакеты и продолжить?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:301
msgid "The server may be overloaded"
msgstr "Возможно, сервер перегружен"

#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Broken packages"
msgstr "Повреждённые пакеты"

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Система содержит повреждённые пакеты, которые не могут быть исправлены "
"данной программой. Пожалуйста, исправьте их, используя synaptic или apt-get, "
"прежде чем продолжить."

#: ../DistUpgrade/DistUpgradeCache.py:660
#, python-format
msgid "Broken packages after upgrade: %s"
msgstr "Пакеты повреждённые после обновления: %s"

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:665
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""
"Во время расчёта обновлений возникла нерешаемая проблема.\n"
"\n"
" "

#: ../DistUpgrade/DistUpgradeCache.py:668
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""
"Вероятно это было вызвано из-за того что:\n"
" * Неофициальные пакеты программного обеспечения не поддерживаются Ubuntu\n"
"Пожалуйста, используйте команду 'ppa-purge' из пакета ppa-purge \n"
"для удаления программного обеспечения из Launchpad PPA и \n"
"попробуйте обновиться ещё раз.\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:676
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""
"Вероятно это было вызвано из-за:\n"
" * Обновления до пред-релизной версии Ubuntu\n"
"Скорее всего, это временная проблема, \n"
"пожалуйста, повторите попытку позже.\n"

#: ../DistUpgrade/DistUpgradeCache.py:683
msgid "This is most likely a transient problem, please try again later."
msgstr "Вероятно, это временная проблема. Попробуйте повторить позднее."

#: ../DistUpgrade/DistUpgradeCache.py:686
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""
"Если ничего из этого не подходит, пожалуйста сообщите об ошибке используя "
"команду 'ubuntu-bug ubuntu-release-upgrader-core' в терминале. "

#: ../DistUpgrade/DistUpgradeCache.py:688
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at "
"'main.log' and 'apt.log'."
msgstr ""
"Если вы хотите разобраться самостоятельно, файлы журнала в '/var/log/dist-"
"upgrade' содержат подробности об обновлении. Особенно, обратите внимание на "
"'main.log' и 'apt.log'."

#: ../DistUpgrade/DistUpgradeCache.py:694
msgid "Could not calculate the upgrade"
msgstr "Не удалось рассчитать обновление системы"

#: ../DistUpgrade/DistUpgradeCache.py:751
msgid "Error authenticating some packages"
msgstr "Ошибка при проверке подлинности некоторых пакетов"

#: ../DistUpgrade/DistUpgradeCache.py:752
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Не удалось проверить подлинность некоторых пакетов. Возможно, это "
"кратковременная проблема с сетью и стоит повторить операцию позже. Ниже "
"приведен список пакетов, не прошедших проверку."

#: ../DistUpgrade/DistUpgradeCache.py:773
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal deny list."
msgstr ""
"Пакет «%s» отмечен для удаления, но он находится в списке пакетов, которые "
"запрещено удалять."

#: ../DistUpgrade/DistUpgradeCache.py:779
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Основной пакет «%s» отмечен для удаления."

#: ../DistUpgrade/DistUpgradeCache.py:788
#, python-format
msgid "Trying to install deny listed version '%s'"
msgstr "Попытка установить запрещённую версию «%s»."

#: ../DistUpgrade/DistUpgradeCache.py:910
#, python-format
msgid "Can't install '%s'"
msgstr "Не удалось установить «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:911
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Невозможно установить требуемый пакет. Сообщите об этой ошибке, выполнив "
"команду «ubuntu-bug ubuntu-release-upgrader-core» в терминале."

#: ../DistUpgrade/DistUpgradeCache.py:922
msgid "Can't guess meta-package"
msgstr "Не удалось подобрать мета-пакет"

#: ../DistUpgrade/DistUpgradeCache.py:923
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"В системе отсутствует пакет %s или %s, поэтому невозможно определить "
"запущенную версию Ubuntu.\n"
" Перед тем, как продолжить, установите один из указанных выше пакетов при "
"помощи synaptic или apt-get."

#: ../DistUpgrade/DistUpgradeController.py:145
msgid "Reading cache"
msgstr "Чтение временных файлов"

#: ../DistUpgrade/DistUpgradeController.py:267
msgid "Unable to get exclusive lock"
msgstr "Не удалось получить исключительную блокировку"

#: ../DistUpgrade/DistUpgradeController.py:268
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Как правило, это означает, что уже запущена другая программа управления "
"пакетами (например, apt-get или aptitude). Пожалуйста, закройте эту "
"программу, чтобы продолжить."

#: ../DistUpgrade/DistUpgradeController.py:326
msgid "Upgrading over remote connection not supported"
msgstr "Обновление через удалённое соединение не поддерживается"

#: ../DistUpgrade/DistUpgradeController.py:327
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Вы пытаетесь выполнить обновление через ssh-соединение с неподдерживаемым "
"клиентом. Обновитесь в текстовом режиме с помощью «do-release-upgrade».\n"
"\n"
"Обновление остановлено. Попробуйте без ssh."

#: ../DistUpgrade/DistUpgradeController.py:341
msgid "Continue running under SSH?"
msgstr "Продолжить работу через SSH?"

#: ../DistUpgrade/DistUpgradeController.py:342
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Этот сеанс запущен через ssh. Не рекомендуется выполнять обновление через "
"ssh, так как в случае неудачи восстановление будет очень сложным.\n"
"\n"
"Если вы продолжите, дополнительная служба ssh будет запущена на порту «%s».\n"
"Хотите ли вы продолжить?"

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Starting additional sshd"
msgstr "Запускается дополнительный sshd"

#: ../DistUpgrade/DistUpgradeController.py:357
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Чтобы сделать восстановление легче в случае ошибки, дополнительная служба "
"sshd будет запущена на порту «%s». Если что-либо случится с используемым "
"ssh, вы сможете подключиться к дополнительной службе.\n"

#: ../DistUpgrade/DistUpgradeController.py:365
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Если у вас включён брандмауэр, вам возможно необходимо временно открыть этот "
"порт. Поскольку это потенциально опасно, порт не открывается автоматически. "
"Вы можете открыть следующий способом:\n"
"«%s» порт."

#: ../DistUpgrade/DistUpgradeController.py:443
#: ../DistUpgrade/DistUpgradeController.py:467
msgid "Can not upgrade"
msgstr "Не удалось обновить"

#: ../DistUpgrade/DistUpgradeController.py:444
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Обновление от «%s» к «%s» не поддерживается этой утилитой."

#: ../DistUpgrade/DistUpgradeController.py:468
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""
"Ваша установка python3 повреждена. Пожалуйста, исправьте символьную ссылку  "
"'/usr/bin/python3'."

#: ../DistUpgrade/DistUpgradeController.py:497
#, python-format
msgid "Can not write to '%s'"
msgstr "Невозможно выполнить запись в '%s'"

#: ../DistUpgrade/DistUpgradeController.py:498
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"Невозможно выполнить запись в системный каталог '%s' в вашей системе. "
"Обновление не может продолжаться.\n"
"Пожалуйста, убедитесь что системный каталог доступен для записи."

#: ../DistUpgrade/DistUpgradeController.py:717
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "Не для людей, пока находится в стадии разработки релиза %s"

#: ../DistUpgrade/DistUpgradeController.py:818
#, python-format
msgid "disabled on upgrade to %s"
msgstr "отключено при обновлении до %s"

#: ../DistUpgrade/DistUpgradeController.py:1251
msgid "No valid source entry found"
msgstr "Не найдено ни одной действительной записи источника"

#: ../DistUpgrade/DistUpgradeController.py:1252
#: ../DistUpgrade/DistUpgradeController.py:1320
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""
"При сканировании вашей информации о репозиториях не найдено записи о %s.\n"
"\n"
"Обновление может оказаться неудачным.\n"
"\n"
"Всё равно продолжить?"

#: ../DistUpgrade/DistUpgradeController.py:1262
#: ../DistUpgrade/DistUpgradeController.py:1330
msgid "No valid mirror found"
msgstr "Не найдено ни одного действующего зеркала"

#: ../DistUpgrade/DistUpgradeController.py:1263
#: ../DistUpgrade/DistUpgradeController.py:1331
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"При сканировании репозитория не было найдено зеркало для обновления. Такое "
"могло произойти в случае использования внутреннего зеркала или информация о "
"зеркалах устарела.\n"
"\n"
"Все равно хотите переписать файл источников 'sources.list'? Если вы укажете "
"\"Да\", то произойдет обновление всех записей от '%s' до '%s'.\n"
"Если укажете \"Нет\" обновление будет прекращено."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:1283
#: ../DistUpgrade/DistUpgradeController.py:1351
msgid "Generate default sources?"
msgstr "Сгенерировать источники по умолчанию?"

#: ../DistUpgrade/DistUpgradeController.py:1284
#, python-format
msgid ""
"After scanning your 'ubuntu.sources' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"После сканирования 'ubuntu.sources' не было найдено ни одной действительной "
"записи для '%s'.\n"
"\n"
"Следует ли добавить записи по умолчанию для '%s'? Если вы выберете \"Нет\", "
"обновление будет отменено."

#: ../DistUpgrade/DistUpgradeController.py:1302
#: ../DistUpgrade/DistUpgradeController.py:1403
msgid "Third party sources disabled"
msgstr "Сторонние источники отключены"

#: ../DistUpgrade/DistUpgradeController.py:1303
#: ../DistUpgrade/DistUpgradeController.py:1404
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Некоторые сторонние источники в файле «sources.list» были отключены. Вы "
"сможете их снова включить после обновления с помощью утилиты «Источники "
"приложений» или вашего менеджера пакетов."

#: ../DistUpgrade/DistUpgradeController.py:1319
msgid "No valid sources.list entry found"
msgstr "Не найдено достоверных записей sources.list"

#: ../DistUpgrade/DistUpgradeController.py:1352
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Не найдена запись для «%s» в файле «sources.list».\n"
"\n"
"Добавить стандартную запись для «%s»? Выбор «Нет» означает отказ от "
"обновления."

#: ../DistUpgrade/DistUpgradeController.py:1387
#: ../DistUpgrade/DistUpgradeController.py:1393
msgid "Repository information invalid"
msgstr "Информация о репозитории неверна"

#: ../DistUpgrade/DistUpgradeController.py:1388
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"Обновление сведений о репозиториях привело к созданию повреждённого файла. "
"Выполняется запуск системы сообщения о неполадке."

#: ../DistUpgrade/DistUpgradeController.py:1394
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Обновление сведений репозиториев привело к созданию недопустимого файла. "
"Чтобы сообщить о неполадке, установите apport и выполните команду 'apport-"
"bug ubuntu-release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:1446
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Пакет в  состоянии"
msgstr[1] "Пакеты в нестабильном состоянии"
msgstr[2] "Пакеты в нестабильном состоянии"

#: ../DistUpgrade/DistUpgradeController.py:1449
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Пакет «%s» в нестабильном состоянии и должен быть переустановлен, однако для "
"него не найден архивный файл. Переустановите пакет вручную, либо удалите его "
"из системы."
msgstr[1] ""
"Пакеты «%s» в нестабильном состоянии и должны быть переустановлены, однако "
"для них не найдены архивные файлы. Переустановите пакеты вручную, либо "
"удалите их из системы."
msgstr[2] ""
"Пакеты «%s» в нестабильном состоянии и должны быть переустановлены, однако "
"для них не найдены архивные файлы. Переустановите пакеты вручную, либо "
"удалите их из системы."

#: ../DistUpgrade/DistUpgradeController.py:1510
msgid "Error during update"
msgstr "Ошибка при обновлении"

#: ../DistUpgrade/DistUpgradeController.py:1511
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"При обновлении возникла проблема. Обычно это бывает вызвано проблемами в "
"сети. Проверьте сетевые подключения и повторите попытку."

#: ../DistUpgrade/DistUpgradeController.py:1554
#: ../DistUpgrade/DistUpgradeController.py:1559
msgid "EFI System Partition (ESP) not usable"
msgstr "Системный раздел EFI (ESP) непригоден для использования"

#: ../DistUpgrade/DistUpgradeController.py:1555
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""
"Системный раздел EFI (ESP) не смонтирован в /boot/efi. Пожалуйста, "
"убедитесь, что он правильно настроен и повторите снова."

#: ../DistUpgrade/DistUpgradeController.py:1560
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""
"Системный раздел EFI (ESP), смонтированный в /boot/efi не доступен для "
"записи. Пожалуйста, перемонтируйте этот раздел в режиме чтения-записи и "
"повторите снова."

#: ../DistUpgrade/DistUpgradeController.py:1567
msgid "Not enough free disk space"
msgstr "Недостаточно свободного места на диске"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1570
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""
"Обновление прервано. Для обновления требуется {str_total} свободного места "
"на диске '{str_dir}'. Освободите не менее {str_needed} дополнительного "
"дискового пространства на '{str_dir}'. {str_remedy}"

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1575
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""
"Удалите временные пакеты от предыдущих установок с помощью «sudo apt clean»."

#: ../DistUpgrade/DistUpgradeController.py:1577
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""
"Можете удалить старые ядра с помощью «sudo apt autoremove» а также задать "
"COMPRESS=xz в /etc/initramfs-tools/initramfs.conf, чтобы уменьшить размер "
"initramfs."

#: ../DistUpgrade/DistUpgradeController.py:1582
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"Очистите корзину и удалите временные пакеты от предыдущих установок командой "
"«sudo apt-get clean»."

#: ../DistUpgrade/DistUpgradeController.py:1585
msgid "Reboot to clean up files in /tmp."
msgstr "Перезагрузите компьютер для удаления файлов из /tmp."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1624
#: ../DistUpgrade/DistUpgradeController.py:2497
#: ../DistUpgrade/DistUpgradeController.py:2549
msgid "Calculating the changes"
msgstr "Расчёт изменений"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1668
msgid "Do you want to start the upgrade?"
msgstr "Вы хотите начать обновление системы?"

#: ../DistUpgrade/DistUpgradeController.py:1687
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""
"Обновления безопасности Livepatch недоступны для Ubuntu %s. Если вы "
"произведёте полное обновление, Livepatch будет отключён."

#: ../DistUpgrade/DistUpgradeController.py:1759
msgid "Upgrade canceled"
msgstr "Обновление отменено"

#: ../DistUpgrade/DistUpgradeController.py:1760
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"Это обновление сейчас будет отменено и произойдет восстановление исходного "
"состояния системы. Вы можете продолжить это обновление позже."

#: ../DistUpgrade/DistUpgradeController.py:1766
#: ../DistUpgrade/DistUpgradeController.py:1911
msgid "Could not download the upgrades"
msgstr "Не удалось загрузить обновления"

#: ../DistUpgrade/DistUpgradeController.py:1767
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"Обновление было прервано. Пожалуйста, проверьте ваше соединение с интернетом "
"или установочный носитель и попробуйте снова. Все загруженные файлы были "
"сохранены."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1860
#: ../DistUpgrade/DistUpgradeController.py:1899
#: ../DistUpgrade/DistUpgradeController.py:2016
msgid "Error during commit"
msgstr "Ошибка при фиксировании"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1862
#: ../DistUpgrade/DistUpgradeController.py:1901
#: ../DistUpgrade/DistUpgradeController.py:2065
msgid "Restoring original system state"
msgstr "Восстановление первоначального состояния системы"

#: ../DistUpgrade/DistUpgradeController.py:1863
#: ../DistUpgrade/DistUpgradeController.py:1878
#: ../DistUpgrade/DistUpgradeController.py:1902
msgid "Could not install the upgrades"
msgstr "Не удалось установить обновления"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1868
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Обновление было отменено. Ваша система может оказаться в непригодном для "
"использования состоянии. Сейчас будет запущен процесс восстановления (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1873
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Сообщите об этой ошибке, открыв в браузере страницу "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug и "
"прикрепив файлы из папки «/var/log/dist-upgrade/» к отчёту.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1912
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Обновление было отменено. Проверьте ваше соединение с интернетом или ваш "
"установочный носитель и попробуйте снова. "

#: ../DistUpgrade/DistUpgradeController.py:1940
msgid "Searching for obsolete software"
msgstr "Поиск устаревших программ"

#: ../DistUpgrade/DistUpgradeController.py:2004
msgid "Remove obsolete packages?"
msgstr "Удалить устаревшие пакеты?"

#: ../DistUpgrade/DistUpgradeController.py:2005
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Оставить"

#: ../DistUpgrade/DistUpgradeController.py:2005
msgid "_Remove"
msgstr "_Удалить"

#: ../DistUpgrade/DistUpgradeController.py:2017
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Во время очистки возникла проблема. Подробности описаны в сообщении ниже. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:2103
msgid "Required depends is not installed"
msgstr "Не установлены требуемые зависимости"

#: ../DistUpgrade/DistUpgradeController.py:2104
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Требуемая зависимость «%s» не установлена. "

#. coherence check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:2337
#: ../DistUpgrade/DistUpgradeController.py:2445
msgid "Checking package manager"
msgstr "Проверка менеджера пакетов"

#: ../DistUpgrade/DistUpgradeController.py:2343
#: ../DistUpgrade/DistUpgradeController.py:2349
msgid "Preparing the upgrade failed"
msgstr "Подготовка к обновлению завершилась неудачно"

#: ../DistUpgrade/DistUpgradeController.py:2344
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Подготовки системы к обновлению не удалась, будет запущена программа отчетов "
"об ошибках."

#: ../DistUpgrade/DistUpgradeController.py:2350
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Подготовка системы к обновлению закончилась сбоем. Чтобы сообщить об ошибке, "
"установите apport и выполните команду 'apport-bug ubuntu-release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:2367
#: ../DistUpgrade/DistUpgradeController.py:2377
msgid "Getting upgrade prerequisites failed"
msgstr "Подготовка к обновлению завершилась неудачно"

#: ../DistUpgrade/DistUpgradeController.py:2368
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"Система не может получить предварительные реквизиты для выполнения полного "
"обновления. Сейчас будет прервано полное обновление и выполнено "
"восстановление исходного состояния системы.\n"
"\n"
"Выполняется запуск системы сообщения о неполадке."

#: ../DistUpgrade/DistUpgradeController.py:2378
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"Не выполнены системные требования для выполнения обновления. Процедура "
"обновления будет отменена, исходное состояние системы будет восстановлено."

#: ../DistUpgrade/DistUpgradeController.py:2412
msgid "Updating repository information"
msgstr "Обновление информации о репозитории"

#: ../DistUpgrade/DistUpgradeController.py:2474
msgid "Invalid package information"
msgstr "Неверная информация о пакете"

#: ../DistUpgrade/DistUpgradeController.py:2475
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"После обновления информации о пакетах, не найден необходимый пакет '%s'. "
"Возможно в ваших источниках приложений отсутствуют официальные зеркала или "
"из-за превышения нагрузки на зеркало, которое вы используете. Проверьте "
"список источников приложений /etc/apt/sources.list\n"
"В случае превышения нагрузки зеркала вы можете повторить попытку обновления "
"позже."

#: ../DistUpgrade/DistUpgradeController.py:2504
#: ../DistUpgrade/DistUpgradeController.py:2615
msgid "Fetching"
msgstr "Загрузка"

#: ../DistUpgrade/DistUpgradeController.py:2511
#: ../DistUpgrade/DistUpgradeController.py:2534
#: ../DistUpgrade/DistUpgradeController.py:2564
#: ../DistUpgrade/DistUpgradeController.py:2619
msgid "Upgrading"
msgstr "Обновление"

#: ../DistUpgrade/DistUpgradeController.py:2513
msgid "Upgrade infeasible"
msgstr "Обновление недопустимо"

#: ../DistUpgrade/DistUpgradeController.py:2514
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr ""
"Невозможно завершить обновление, так как в процессе обновления возникли "
"ошибки."

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2537
#: ../DistUpgrade/DistUpgradeController.py:2553
msgid "Upgrade incomplete"
msgstr "Неполное обновление"

#: ../DistUpgrade/DistUpgradeController.py:2538
#: ../DistUpgrade/DistUpgradeController.py:2554
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""
"Обновление частично завершено, однако в процессе обновления выявлены ошибки."

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2569
#: ../DistUpgrade/DistUpgradeController.py:2621
#: ../DistUpgrade/DistUpgradeController.py:2627
#: ../DistUpgrade/DistUpgradeController.py:2638
msgid "Upgrade complete"
msgstr "Обновление завершено"

#: ../DistUpgrade/DistUpgradeController.py:2570
#: ../DistUpgrade/DistUpgradeController.py:2622
#: ../DistUpgrade/DistUpgradeController.py:2628
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""
"Обновление завершено, но во время процесса обновления произошли ошибки."

#: ../DistUpgrade/DistUpgradeController.py:2585
msgid "System upgrade is complete."
msgstr "Обновление системы завершено."

#: ../DistUpgrade/DistUpgradeController.py:2639
msgid "The partial upgrade was completed."
msgstr "Частичное обновление завершено."

#: ../DistUpgrade/DistUpgradeController.py:2660
msgid "Lock screen disabled"
msgstr "Блокировка экрана отключена"

#: ../DistUpgrade/DistUpgradeController.py:2661
msgid ""
"Your lock screen has been disabled and will remain disabled during the "
"upgrade."
msgstr ""
"Экран блокировки был отключён и останется отключённым во время обновления."

#: ../DistUpgrade/DistUpgradeController.py:2669
msgid "Unable to disable lock screen"
msgstr "Невозможно отключить экран блокировки"

#: ../DistUpgrade/DistUpgradeController.py:2670
msgid ""
"It is highly recommended that the lock screen be disabled during the upgrade "
"to prevent later issues. Please ensure your screen lock is disabled before "
"continuing."
msgstr ""
"Настоятельно рекомендуется отключить экран блокировки на время обновления, "
"чтобы предотвратить возможные проблемы. Прежде чем продолжить, убедитесь, "
"что блокировка экрана отключена."

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "Не удалось найти примечания к выпуску"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "Возможно, сервер перегружен. "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "Не удалось загрузить примечания к выпуску"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherCore.py:77
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "Пожалуйста, проверьте ваше сетевое соединение."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:72
msgid "Could not find the release announcement"
msgstr "Объявление о выпуске не найдено"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
msgid "The server may be overloaded."
msgstr "Возможно сервер перегружен."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:76
msgid "Could not download the release announcement"
msgstr "Объявление о выпуске не скачано"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:82
#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "Продолжить [дН] "

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeFetcherCore.py:84
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "д"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:101
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "аутентифицировать '%(file)s' вместо '%(signature)s' "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:127
#, python-format
msgid "extracting '%s'"
msgstr "извлечение '%s'"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:148
#: ../DistUpgrade/DistUpgradeFetcherCore.py:149
msgid "Could not run the upgrade tool"
msgstr "Не удалось запустить утилиту обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:150
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"Скорее всего, это ошибка в программе обновления. Пожалуйста, сообщите о ней, "
"выполнив команду «ubuntu-bug ubuntu-release-upgrader-core» в терминале."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:227
msgid "Upgrade tool signature"
msgstr "Подпись утилиты обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
msgid "Upgrade tool"
msgstr "Утилита обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:268
msgid "Failed to fetch"
msgstr "Не удалось получить"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "Не удалось получить обновление. Возможно, возникла проблема в сети. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:273
msgid "Authentication failed"
msgstr "Проверка подлинности не удалась"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:274
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Проверка подлинности обновления не удалась. Возможно, возникла проблема в "
"сети или на сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:279
msgid "Failed to extract"
msgstr "Не удалось извлечь"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Не удалось извлечь обновление. Возможно, возникла проблема в сети или на "
"сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:285
msgid "Verification failed"
msgstr "Проверка не удалась"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Проверка обновления завершилась неудачно. Возможно, возникла проблема в сети "
"или на сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:300
#: ../DistUpgrade/DistUpgradeFetcherCore.py:306
msgid "Can not run the upgrade"
msgstr "Не удалось запустить процесс обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:301
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Обычно возникает в системе, где /tmp смонтирован с флагом noexec. "
"Пожалуйста, перемонтируйте без флага noexec и запустите обновление снова."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:307
#, python-format
msgid "The error message is '%s'."
msgstr "Сообщение об ошибке «%s»."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr "&Обновление"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
msgid "&Cancel"
msgstr "&Отменить"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Примечания к выпуску"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "Обновление"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "Загрузка дополнительных файлов пакетов..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Файл %s из %s на скорости %sБ/с"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "Файл %s из %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:127
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Вставьте «%s» в привод «%s»"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "Смена носителя"

#: ../DistUpgrade/DistUpgradeQuirks.py:246
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr ""
"Имеющееся графическое оборудование может не полностью поддерживаться в "
"Ubuntu 14.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:248
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Do you still "
"want to continue with the upgrade?"
msgstr ""
"Запуск Unity поддерживается вашим графическим оборудованием лишь частично. "
"Поэтому, после обновления, вы можете получить очень медленную систему. Мы "
"советуем вам пока оставаться на LTS версии. Для большей информации посетите "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D  Вы все еще "
"хотите начать обновление?"

#: ../DistUpgrade/DistUpgradeQuirks.py:272
msgid ""
"Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Ваша видеокарта не будет поддерживаться полностью в Ubuntu 12.04 LTS."

#: ../DistUpgrade/DistUpgradeQuirks.py:274
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"Поддержка вашей видеокарты в Ubuntu 12.04 LTS будет ограниченной и вы можете "
"столкнуться с проблемами после обновления. Прочтите подробности  "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Вы действительно "
"хотите продолжить обновление?"

#: ../DistUpgrade/DistUpgradeQuirks.py:294
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"Обновление может повлечь снижение качества эффектов рабочего стола и "
"производительности в играх и приложениях, активно работающих с графикой."

#: ../DistUpgrade/DistUpgradeQuirks.py:298
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"На этом компьютере используются драйвера AMD «fglrx».  Нет доступных версий "
"этих драйверов, которые бы работали с вашим оборудованием в Ubuntu 10.04 "
"LTS.\n"
"\n"
"Вы хотите продолжить?"

#: ../DistUpgrade/DistUpgradeQuirks.py:337
#: ../DistUpgrade/DistUpgradeQuirks.py:406
msgid "Sorry, no more upgrades for this system"
msgstr "Извините, больше нет обновлений для этой системы"

#: ../DistUpgrade/DistUpgradeQuirks.py:338
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""
"Не будет больше выпусков Ubuntu для архитектуры этой системы 'i386'.\n"
"\n"
"Обновления для Ubuntu %s будут продолжаться до %s."

#: ../DistUpgrade/DistUpgradeQuirks.py:353
msgid "No ARMv6 CPU"
msgstr "Нет процессора ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:354
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Ваша система использует процессор архитектуры ARM, старше архитектуры ARMv6. "
"Все пакеты в karmic были собраны с оптимизацией под архитектуру ARMv6 и "
"выше. Вашу систему невозможно обновить до нового релиза Ubuntu с текущим "
"аппаратным обеспечением."

#: ../DistUpgrade/DistUpgradeQuirks.py:374
msgid ""
"Sorry, this storage driver is not supported in kernels for newer releases"
msgstr ""
"Этот драйвер запоминающего устройства не поддерживается в ядрах новых "
"выпусков."

#: ../DistUpgrade/DistUpgradeQuirks.py:376
#, python-format
msgid ""
"There will not be any further Ubuntu releases that provide kernel support "
"for the aufs storage driver.\n"
"\n"
"Please ensure that none of your containers are using the aufs storage "
"driver, remove the directory %s and try again."
msgstr ""
"Больше не будет выпусков Ubuntu, которые обеспечивают поддержку ядра для "
"драйвера файловой системы aufs.\n"
"\n"
"Убедитесь, что ни один из контейнеров не использует драйвер файловой системы "
"aufs, удалите каталог %s и повторите попытку."

#: ../DistUpgrade/DistUpgradeQuirks.py:407
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's POWER8 "
"processor.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""
"Больше не будет выпусков Ubuntu для процессора POWER8.\n"
"\n"
"Обновления для Ubuntu %s будут выходить до %s."

#: ../DistUpgrade/DistUpgradeQuirks.py:425
msgid "No init available"
msgstr "Служба init недоступна"

#: ../DistUpgrade/DistUpgradeQuirks.py:426
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Похоже, что ваша система является виртуализованным окружением без службы "
"init, например Linux-VServer. Ubuntu 10.04 LTS не может работать в таком "
"типе окружения, вы должны вначале исправить конфигурацию своей виртуальной "
"машины.\n"
"\n"
"Вы уверены, что хотите продолжить?"

#: ../DistUpgrade/DistUpgradeQuirks.py:467
msgid "The Robot Operating System (ROS) is installed"
msgstr "Установлена операционная система для роботов (ROS)"

#: ../DistUpgrade/DistUpgradeQuirks.py:468
msgid ""
"It appears that ROS is currently installed. Each ROS release is very strict "
"about the versions of Ubuntu it supports, and Ubuntu upgrades can fail if "
"that guidance isn't followed. Before continuing, please either uninstall "
"ROS, or ensure the ROS release you have installed supports the version of "
"Ubuntu to which you're upgrading.\n"
"\n"
"For ROS 1 releases, refer to REP 3:\n"
"https://www.ros.org/reps/rep-0003.html\n"
"\n"
"For ROS 2 releases, refer to REP 2000:\n"
"https://www.ros.org/reps/rep-2000.html\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Похоже, что в настоящее время установлена ROS. Каждый выпуск ROS предъявляет "
"строгие требования к поддерживаемым версиям Ubuntu, и обновление Ubuntu без "
"следования руководствам может повредить её. Перед тем, как продолжить, либо "
"удалите ROS, либо убедитесь, что установленный выпуск ROS поддерживает "
"версию Ubuntu, на которую вы обновляетесь.\n"
"\n"
"Для выпусков ROS 1 обратитесь к REP 3:\n"
"https://www.ros.org/reps/rep-0003.html\n"
"\n"
"Для выпусков ROS 2 обратитесь к REP 2000:\n"
"https://www.ros.org/reps/rep-2000.html\n"
"\n"
"Вы действительно хотите продолжить?"

#: ../DistUpgrade/DistUpgradeQuirks.py:661
msgid "Connection to the Snap Store failed"
msgstr "Не удалось подключиться к магазину Snap Store"

#: ../DistUpgrade/DistUpgradeQuirks.py:662
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""
"У вас установлен пакет lxd, но вашей системе не удалось подключиться к "
"магазину Snap Store. В настоящее время lxd предоставляется snap-пакетом и "
"его полное обновление не удастся, если не функционирует snapd. Пожалуйста, "
"убедитесь, что вы подключены к интернету, обновите настройки брандмауэра или "
"прокси-сервера таким образом, чтобы api.snapcraft.io был доступен. Если "
"используется в корпоративном сегменте с установленным брандмауэром, вероятно "
"вы захотите настроить прокси-сервер магазина Snap Store."

#: ../DistUpgrade/DistUpgradeQuirks.py:677
msgid "Connection to Snap Store failed"
msgstr "Не удалось подключиться к Snap Store"

#: ../DistUpgrade/DistUpgradeQuirks.py:678
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to "
"api.snapcraft.io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""
"Ваша система не имеет подключения к Snap Store. Для обеспечения наилучшего "
"обновления убедитесь, что ваша система может подключаться к "
"api.snapcraft.io.\n"
"Вы все еще хотите продолжить обновление?"

#: ../DistUpgrade/DistUpgradeQuirks.py:687
msgid "Outdated snapd package"
msgstr "Устаревший пакет snapd"

#: ../DistUpgrade/DistUpgradeQuirks.py:688
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""
"В вашей системе нет последней версии snapd. Обновите версию snapd в вашей "
"системе, чтобы улучшить процесс обновления.\n"
"Вы все еще хотите продолжить обновление?"

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:713
msgid "Calculating snap size requirements"
msgstr "Расчёт требуемого размера snap"

#: ../DistUpgrade/DistUpgradeQuirks.py:744
msgid "Processing snap replacements"
msgstr "Обработка замещений snap"

#. TODO: This status should be updated, but the time of
#. this change to snap switch is post-translation freeze.
#: ../DistUpgrade/DistUpgradeQuirks.py:752
#, python-format
msgid "refreshing snap %s"
msgstr "обновление snap-пакета %s"

#: ../DistUpgrade/DistUpgradeQuirks.py:756
#, python-format
msgid "removing snap %s"
msgstr "удаление snap-пакета %s"

#: ../DistUpgrade/DistUpgradeQuirks.py:759
#, python-format
msgid "installing snap %s"
msgstr "установка snap-пакета %s"

#: ../DistUpgrade/DistUpgradeQuirks.py:788
msgid "PAE not enabled"
msgstr "PAE отключен"

#: ../DistUpgrade/DistUpgradeQuirks.py:789
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""
"Ваша система использует ЦПУ без включённого режима PAE. Ubuntu поддерживает "
"системы не использующие PAE только до выпуска Ubuntu 12.04. Чтобы обновить "
"выпуск Ubuntu до актуального, вам необходимо задействовать PAE (если это "
"возможно), обратитесь к веб-сайту:\n"
"http://help.ubuntu.com/community/EnablingPAE"

#: ../DistUpgrade/DistUpgradeQuirks.py:1085
msgid "universe component not enabled"
msgstr "компонент universe не задействован"

#: ../DistUpgrade/DistUpgradeQuirks.py:1086
#, python-format
msgid ""
"You have the package %s installed which is a python2 package. python2 has "
"been deprecated in Ubuntu 20.04 LTS and is now available from the universe "
"component of the Ubuntu archive. To ensure any existing third party code you "
"have installed continues to work the release upgrade process would install "
"%s for you. However, the universe component of the archive is not enabled on "
"this system. For the upgrade process to proceed you should either enable the "
"universe component in /etc/apt/sources.list or remove %s"
msgstr ""
"Установлен пакет %s, который является пакетом python2. python2 был объявлен "
"устаревшим в Ubuntu 20.04 LTS и сейчас доступен в компоненте universe архива "
"Ubuntu. Чтобы любой установленный сторонний код продолжал работать, процесс "
"обновления выпуска установит %s. Тем не менее, компонент universe не "
"задействован в этой системе. Для продолжения обновления необходимо "
"задействовать компонент universe в файле /etc/apt/sources.list или удалить "
"%s."

#: ../DistUpgrade/DistUpgradeQuirks.py:1198
msgid "Checking for installed snaps"
msgstr "Проверка установленных snap"

#: ../DistUpgrade/DistUpgradeQuirks.py:1645
msgid "Cannot upgrade this system"
msgstr "Невозможно обновить эту систему"

#: ../DistUpgrade/DistUpgradeQuirks.py:1646
msgid ""
"Due to a bug in grub, this system cannot be safely upgraded at this time.\n"
"\n"
"See https://launchpad.net/bugs/2039172."
msgstr ""
"Из-за ошибки в grub, в настоящее время система не может быть безопасно "
"обновлена полностью.\n"
"\n"
"См. https://launchpad.net/bugs/2039172."

#: ../DistUpgrade/DistUpgradeQuirks.py:1710
#, python-brace-format
msgid "Updates for Ubuntu {from_release.version} will "
msgstr "Обновления для Ubuntu {from_release.version} "

#: ../DistUpgrade/DistUpgradeQuirks.py:1720
msgid "Sorry, cannot upgrade this system to 24.04 LTS"
msgstr "Извините, эту систему нельзя обновить до 24.04 LTS"

#: ../DistUpgrade/DistUpgradeQuirks.py:1723
msgid ""
"The Raspberry Pi kernel for Ubuntu 24.04 LTS does not support the armhf "
"architecture.\n"
"\n"
msgstr ""
"Ядро Raspberry Pi для Ubuntu 24.04 LTS не поддерживает архитектуру armhf.\n"
"\n"

#: ../DistUpgrade/DistUpgradeMain.py:62
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Использовать интерфейс. Сейчас доступны: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "*DEPRECATED* this option will be ignored"
msgstr "Этот параметр *УСТАРЕЛ* и не будет учитываться"

#: ../DistUpgrade/DistUpgradeMain.py:68
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Подготовить только частичное обновление (sources.list перезаписан не будет)"

#: ../DistUpgrade/DistUpgradeMain.py:71
msgid "Disable GNU screen support"
msgstr "Отключить поддержку экрана GNU"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Set datadir"
msgstr "Установить каталог с данными"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "Upgrade to the development release"
msgstr "Обновиться до разрабатываемого выпуска"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:148
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "Загрузка завершена"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Загрузка файла %li из %li на скорости %s Байт/сек"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:165
#: ../DistUpgrade/DistUpgradeViewGtk3.py:327
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "Осталось приблизительно %s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:168
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "Загрузка файла %li из %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:200
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "Применение изменений"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:226
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "проблемы зависимостей — оставляем не настроенным"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "Не удалось установить «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"Обновление будет продолжено, но пакет «%s»  может быть в нерабочем "
"состоянии. Просьба рассмотреть вопрос о представлении отчёта об этой ошибке."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:249
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Заменить изменённый конфигурационный файл\n"
"«%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:250
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Вы потеряете все изменения, которые сделали в этом файле конфигурации, если "
"замените его новой версией."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:270
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "Команда «diff» не найдена"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:542
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "Произошла критическая ошибка"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:543
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Пожалуйста, сообщите об этом как об ошибке (если вы ещё этого не сделали) и "
"включите файлы /var/log/dist-upgrade/main.log и /var/log/dist-"
"upgrade/apt.log в ваш отчёт. Обновление было отменено.\n"
"Ваш оригинальный файл sources.list был сохранён в "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:573
msgid "Ctrl-c pressed"
msgstr "Нажаты Ctrl+C"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:574
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Операция будет отменена, что может привести к нерабочему состоянию системы. "
"Вы действительно хотите продолжить?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:713
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Чтобы избежать потерь данных, закройте все открытые приложения и документы."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:727
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Больше не поддерживается компанией Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:728
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Установка старой версии (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:729
#, python-format
msgid "Remove (%s)"
msgstr "Удаление (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:730
#, python-format
msgid "No longer needed (%s)"
msgstr "Больше не нужен (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:731
#, python-format
msgid "Install (%s)"
msgstr "Установка (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:732
#, python-format
msgid "Upgrade (%s)"
msgstr "Обновление (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:780
msgid "Cancel"
msgstr "Отменить"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:781
#: ../DistUpgrade/DistUpgradeViewKDE.py:914
msgid "Continue"
msgstr "Продолжить"

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "Показать различия >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< Скрыть различия"

#: ../DistUpgrade/DistUpgradeViewKDE.py:676
msgid "Error"
msgstr "Ошибка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:728
msgid "Show Terminal >>>"
msgstr "Показать терминал >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:731
msgid "<<< Hide Terminal"
msgstr "<<< Скрыть терминал"

#: ../DistUpgrade/DistUpgradeViewKDE.py:804
msgid "Information"
msgstr "Сведения"

#: ../DistUpgrade/DistUpgradeViewKDE.py:852
msgid "&Start Upgrade"
msgstr "&Начать обновление"

#: ../DistUpgrade/DistUpgradeViewKDE.py:854
#: ../DistUpgrade/DistUpgradeViewKDE.py:898
#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Подробности"

#: ../DistUpgrade/DistUpgradeViewKDE.py:876
#, python-format
msgid "No longer supported %s"
msgstr "Больше не поддерживается (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:878
#, python-format
msgid "Remove %s"
msgstr "Удалить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:880
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Удалить %s (было установлено автоматически)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:882
#, python-format
msgid "Install %s"
msgstr "Установить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:884
#, python-format
msgid "Upgrade %s"
msgstr "Обновить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:931
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "Требуется перезагрузка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:931
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Для завершения обновления перезагрузите систему</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:934
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "_Перезагрузить сейчас"

#: ../DistUpgrade/DistUpgradeViewKDE.py:935
msgid "&Close"
msgstr "&Закрыть"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:952
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Прервать обновление?</big></b>\n"
"\n"
"Если вы прервёте обновление, система может работать нестабильно. "
"Настоятельно рекомендуем продолжить обновление."

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "Cancel Upgrade?"
msgstr "Отменить обновление?"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li день"
msgstr[1] "%li дня"
msgstr[2] "%li дней"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li час"
msgstr[1] "%li часа"
msgstr[2] "%li часов"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li минута"
msgstr[1] "%li минуты"
msgstr[2] "%li минут"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li секунда"
msgstr[1] "%li секунды"
msgstr[2] "%li секунд"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 40Mbit connection and about %s with "
"a 5Mbit connection."
msgstr ""
"Скачивание займёт около %s при 40 Mбит соединении и порядка %s при 5 Mбит "
"соединении."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Загрузка займёт примерно %s на вашем соединении. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "Подготовка к обновлению"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "Получение новых источников приложений"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "Загрузка новых пакетов"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "Установка обновлений"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "Очистка"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d установленный пакет больше не поддерживаются Canonical. Вы можете "
"получить поддержку у сообщества."
msgstr[1] ""
"%(amount)d установленных пакетов больше не поддерживаются Canonical. Вы "
"можете получить поддержку у сообщества."
msgstr[2] ""
"%(amount)d установленных пакетов больше не поддерживаются Canonical. Вы "
"можете получить поддержку у сообщества."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d пакет будет удалён."
msgstr[1] "%d пакета будут удалены."
msgstr[2] "%d пакетов будут удалены."

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d новый пакет будет установлен."
msgstr[1] "%d новых пакета будут установлены."
msgstr[2] "%d новых пакетов будут установлены."

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d пакет будет обновлён."
msgstr[1] "%d пакета будут обновлены."
msgstr[2] "%d пакетов будут обновлены."

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Всего требуется загрузить %s. "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"Установка обновления может занять несколько часов. После завершения загрузки "
"отменить установку будет нельзя."

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Загрузка и установка обновления может занять несколько часов. Когда загрузка "
"завершится, отменить процесс будет невозможно."

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "Удаление пакетов может занять несколько часов. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "Программное обеспечение на этом компьютере актуально."

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Для вашей системы не доступно ни одно обновление. Обновление будет отменено."

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "Требуется перезагрузка"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Обновление завершено и требуется перезагрузка. Перезагрузиться сейчас?"

#: ../DistUpgrade/DistUpgradeView.py:434
msgid "Action required"
msgstr "Требуется действие"

#: ../DistUpgrade/DistUpgradeView.py:435
msgid "Exit all other instances of Ubuntu WSL before continuing."
msgstr "Перед продолжением выйдите из всех других экземпляров Ubuntu WSL."

#: ../DistUpgrade/DistUpgradeView.py:436
msgid "Unsaved progress may otherwise be lost."
msgstr "Иначе несохранённые изменения могут быть потеряны."

#: ../DistUpgrade/DistUpgradeView.py:439
msgid "WSL restart required"
msgstr "Требуется перезапуск WSL"

#: ../DistUpgrade/DistUpgradeView.py:440
msgid "Exit this instance of Ubuntu WSL."
msgstr "Выйдите из этого экземпляра Ubuntu WSL."

#: ../DistUpgrade/DistUpgradeView.py:441
msgid "The upgrade will then be complete."
msgstr "После этого обновление будет завершено."

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr "Выполнено: [%3i%%]"

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Пожалуйста, сообщите об этой ошибке и включите файлы /var/log/dist-"
"upgrade/main.log и /var/log/dist-upgrade/apt.log в ваш отчёт. Обновление "
"было отменено.\n"
"Ваш оригинальный файл sources.list был сохранён в "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "Прерывание"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "Понижено:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "Для продолжения нажмите ввод [ENTER]"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "Подробности [п]"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "н"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "п"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "Больше не поддерживается: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "Удалить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "Установить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "Обновить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "Продолжить [Дн] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Чтобы завершить обновление, требуется перезагрузка.\n"
"Если вы выберите «д», система будет перезагружена."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Загрузка файла %(current)li из %(total)li со скоростью %(speed)s/с"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Загрузка файла %(current)li из %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Показывать прогресс для отдельных файлов"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "_Отменить обновление"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Продолжить обновление"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Прервать текущее обновление?</big></b>\n"
"\n"
"Если вы прервёте обновление, система может оказаться в неработоспособном "
"состоянии. Настоятельно рекомендуется продолжить обновление."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Начать обновление"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Заменить"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Различие между файлами"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "_Сообщить об ошибке"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Продолжить"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Начать обновление?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Перезагрузите систему для завершения обновления.</big></b>\n"
"\n"
"Пожалуйста, сохраните свои документы перед продолжением."

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Обновление дистрибутива"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>Обновление Ubuntu до версии %s</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "Установка новых источников приложений"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "Перезагрузка системы"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "Терминал"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Обновить"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Доступна новая версия Ubuntu. Хотите обновить?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "Не обновлять"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Спросить позже"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Да, обновить сейчас"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Вы отклонили обновление до новой версии Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Вы можете произвести обновление позже, открыв Центр обновлений и нажав "
"\"Обновить\"."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "Выполнить обновление выпуска"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Для обновления Ubuntu вам нужно представиться."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "Выполнить частичное обновление"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "Для частичного обновления вам нужно представиться."

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "Показать версию и выйти"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "Каталог, который содержит файлы данных"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "Запустить указанный интерфейс"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "Идёт частичное обновление"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "Загрузка программы для обновления дистрибутива"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr ""
"Если используется последний поддерживаемый выпуск, обновление до "
"разрабатываемого выпуска"

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:188
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Попробуйте обновиться до самого последнего выпуска с помощью $distro-proposed"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Запустить в специальном режиме обновления.\n"
"В настоящее время поддерживается регулярное обновление для настольных и "
"серверных систем."

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Проверять наличие новой версии дистрибутива и возвращать результат с помощью "
"кода выхода"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""
"Попробуйте произвести полное обновление, используя зеркала предоставленные "
"третьими лицами и репозитории, вместо их комментирования."

#: ../do-release-upgrade:114
msgid ""
"A comma-separated list of environment variables (e.g. "
"VAR1=VALUE1,VAR2=VALUE2) that should be set during the upgrade."
msgstr ""
"Список переменных среды через запятую (например, "
"ПЕР1=ЗНАЧЕНИЕ1,ПЕР2=ЗНАЧЕНИЕ2) для установки во время обновления."

#: ../do-release-upgrade:126
msgid "The options --devel-release and --proposed are"
msgstr "Параметры --devel-release и --proposed являются"

#: ../do-release-upgrade:127
msgid "mutually exclusive. Please use only one of them."
msgstr "взаимоисключающими. Используйте только один из них."

#: ../do-release-upgrade:131
msgid "Checking for a new Ubuntu release"
msgstr "Проверка наличия нового релиза Ubuntu"

#: ../do-release-upgrade:143
msgid "Your Ubuntu release is not supported anymore."
msgstr "Ваша версия  Ubuntu больше не поддерживается."

#: ../do-release-upgrade:144
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Для получения информации об обновлении посетите:\n"
"%(url)s\n"

#: ../do-release-upgrade:159
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr "В системном окне /etc/update-manager/release-upgrade "

#: ../do-release-upgrade:160
msgid "is set to never so upgrading is not possible."
msgstr "выбрано никогда, поэтому обновление невозможно."

#: ../do-release-upgrade:162
msgid "There is no development version of an LTS available."
msgstr "Нет доступной LTS версии для разработчиков."

#: ../do-release-upgrade:163
msgid "To upgrade to the latest non-LTS development release "
msgstr ""
"Чтобы произвести полное обновление до последнего разрабатываемого (без "
"долгосрочной поддержки) выпуска "

#: ../do-release-upgrade:164
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr "установите Prompt=normal в /etc/update-manager/release-upgrades."

#: ../do-release-upgrade:166
msgid "Upgrades to the development release are only "
msgstr "Обновление только до разрабатываемого выпуска "

#: ../do-release-upgrade:167
msgid "available from the latest supported release."
msgstr "доступно только с последнего поддерживаемого выпуска."

#: ../do-release-upgrade:169
msgid "No new release found."
msgstr "Новых выпусков не найдено."

#: ../do-release-upgrade:174
msgid "Release upgrade not possible right now"
msgstr "Обновление релиза сейчас не возможно"

#: ../do-release-upgrade:175
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"Обновление релиза сейчас не может быть выполнено, попробуйте позже. Сервер "
"сообщил: «%s»"

#: ../do-release-upgrade:181
#, c-format
msgid "New release '%s' available."
msgstr "Доступна новая версия «%s»."

#: ../do-release-upgrade:182
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Чтобы обновиться до него, выполните «do-release-upgrade»."

#: ../do-release-upgrade:199
msgid ""
"Please install all available updates for your release before upgrading."
msgstr ""
"Перед обновлением установите все доступные обновления для своей версии."

#: ../do-release-upgrade:215
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""
"Вы не перезагрузились после обновления пакета, требующего перезагрузки. "
"Перед обновлением перезагрузитесь."

#: ../check_new_release_gtk.py:88
msgid "Software Updater"
msgstr "Обновление приложений"

#: ../check_new_release_gtk.py:120
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Доступно обновление Ubuntu %(version)s"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:151
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Вы отклонили обновление до Ubuntu %s"

#: ../check_new_release_gtk.py:184
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Проверка возможности обновления до последней нестабильной версии дистрибутива"

#: ../check_new_release_gtk.py:193
msgid "Add debug output"
msgstr "Добавить результаты отладки"
