msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2021-02-04 21:01+0100\n"
"PO-Revision-Date: 2021-12-25 23:30\n"
"Last-Translator: \n"
"Language-Team: Belarusian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2021-12-22 06:31+0000\n"
"X-Generator: Launchpad (build adb364d6a74a28e7b95d51cd30446ec16160de6c)\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || n%10>=5 && n%10<=9 || n%100>=11 && n%100<=14 ? 2 : 3);\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: be\n"
"X-Crowdin-File: /main/jammy/en_GB/po_apt-listchanges-be.po\n"
"X-Crowdin-File-ID: 629\n"
"Language: be_BY\n"

#: ../apt-listchanges.py:70
#, python-format
msgid "Unknown frontend: %s"
msgstr ""

#: ../apt-listchanges.py:86
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr ""

#: ../apt-listchanges.py:142
#, python-format
msgid "News for %s"
msgstr ""

#: ../apt-listchanges.py:144
#, python-format
msgid "Changes for %s"
msgstr ""

#: ../apt-listchanges.py:154
msgid "Informational notes"
msgstr ""

#: ../apt-listchanges.py:161
msgid "apt-listchanges: News"
msgstr ""

#: ../apt-listchanges.py:162
msgid "apt-listchanges: Changelogs"
msgstr ""

#: ../apt-listchanges.py:168
#, python-format
msgid "apt-listchanges: news for %s"
msgstr ""

#: ../apt-listchanges.py:169
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr ""

#: ../apt-listchanges.py:175
msgid "Didn't find any valid .deb archives"
msgstr ""

#: ../apt-listchanges.py:194
#, python-format
msgid "%s: will be newly installed"
msgstr ""

#: ../apt-listchanges.py:221
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr ""

#: ../apt-listchanges.py:225
#, python-format
msgid "%(pkg)s: Version %(version)s is lower than version of related packages (%(maxversion)s)"
msgstr ""

#: ../apt-listchanges.py:279
msgid "Binary NMU of"
msgstr ""

#: ../apt-listchanges.py:313
#, python-format
msgid "Received signal %d, exiting"
msgstr ""

#: ../apt-listchanges/ALCApt.py:54
msgid "APT pipeline messages:"
msgstr ""

#: ../apt-listchanges/ALCApt.py:62
msgid "Packages list:"
msgstr ""

#: ../apt-listchanges/ALCApt.py:70
msgid "APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""

#: ../apt-listchanges/ALCApt.py:76
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr ""

#: ../apt-listchanges/ALCApt.py:79
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""

#: ../apt-listchanges/ALCApt.py:82
msgid "Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly updated."
msgstr ""

#: ../apt-listchanges/ALCApt.py:87
msgid "APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater than 2)."
msgstr ""

#: ../apt-listchanges/ALCApt.py:93
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/ALCApt.py:99
msgid "Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:116
#, python-format
msgid "Unknown configuration file option: %s"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:129
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:135
#, python-format
msgid "Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""

#: ../apt-listchanges/ALCConfig.py:147
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:150
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:153
#, python-format
msgid "%(deb)s is not readable"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:254
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:262
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:268
msgid "--latest=<N> and --show-all are mutually exclusive"
msgstr ""

#: ../apt-listchanges/ALCLog.py:29 ../apt-listchanges/ALCLog.py:35
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr ""

#: ../apt-listchanges/ALCLog.py:32
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:54
msgid "Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:65
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:74
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:40
msgid "apt-listchanges: Reading changelogs"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:41
msgid "Reading changelogs. Please wait."
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:74
msgid "Continue Installation?"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid "Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt-listchanges/DebianFiles.py:118 ../apt-listchanges/DebianFiles.py:127
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:342
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:417
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:421
#, python-format
msgid "Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed with: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:427
#, python-format
msgid "Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get changelog': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:54
msgid "Aborting"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:59
#, python-format
msgid "Confirmation failed: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:63
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:83
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:92
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:98
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:111
msgid "Available apt-listchanges frontends:"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:113
msgid "Choose a frontend by entering its number: "
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:122
#: ../apt-listchanges/apt_listchanges.py:468
#, python-format
msgid "Error: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:124
#, python-format
msgid "Using default frontend: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:177
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:197
#, python-format
msgid "The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:298
msgid "Do you want to continue? [Y/n] "
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:311
#: ../apt-listchanges/apt_listchanges.py:364
#: ../apt-listchanges/apt_listchanges.py:372
msgid "Reading changelogs"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:350
#: ../apt-listchanges/apt_listchanges.py:405
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:372
msgid "Done"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:450
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:496
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:502
msgid "Cannot find suitable user to drop root privileges"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:528
#, python-format
msgid "None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:558
msgid "press q to quit"
msgstr ""

#: ../apt-listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr ""

#: ../apt-listchanges/apt-listchanges.ui:43
msgid "The following changes are found in the packages you are about to install:"
msgstr ""

